CREATE TYPE user_role AS ENUM ('OWNER','ADMIN','MODERATOR','SUPPORT','USER');
CREATE TYPE file_state AS ENUM ('PROCESSING','AVAILABLE','QUARANTINED','BLOCKED','DELETED','EXPIRED','PURGED');
CREATE TYPE upload_state AS ENUM ('CREATED','UPLOADING','FINALIZING','AVAILABLE','FAILED','ABORTED','EXPIRED');
CREATE TABLE roles(name user_role PRIMARY KEY);
INSERT INTO roles SELECT unnest(enum_range(NULL::user_role));
CREATE TABLE permissions(role user_role REFERENCES roles(name), permission text, PRIMARY KEY(role,permission));
INSERT INTO permissions VALUES ('OWNER','*'),('ADMIN','admin'),('MODERATOR','moderate'),('SUPPORT','support'),('USER','files');
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text UNIQUE, name text NOT NULL, password_hash text, role user_role NOT NULL DEFAULT 'USER' REFERENCES roles(name), anonymous boolean NOT NULL DEFAULT false, status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','SUSPENDED','BANNED')), quota jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, ip text, user_agent text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX sessions_user ON sessions(user_id);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE password_resets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, expires_at timestamptz NOT NULL, consumed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE folders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES users(id), parent_id uuid REFERENCES folders(id), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 255), deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX folders_owner_parent ON folders(owner_id,parent_id);
CREATE TABLE storage_backends(id text PRIMARY KEY, type text NOT NULL, bucket text NOT NULL, enabled boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
INSERT INTO storage_backends(id,type,bucket) VALUES('primary','s3','astrafile');
CREATE TABLE file_objects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), backend_id text NOT NULL REFERENCES storage_backends(id) DEFAULT 'primary', object_key text UNIQUE NOT NULL, expected_size bigint NOT NULL CHECK(expected_size>0), size bigint, etag text, sha256 text, checksum_sha256 text, detected_mime text, state file_state NOT NULL DEFAULT 'PROCESSING', created_at timestamptz NOT NULL DEFAULT now(), verified_at timestamptz);
CREATE TABLE files(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES users(id), object_id uuid NOT NULL REFERENCES file_objects(id), folder_id uuid REFERENCES folders(id), name text NOT NULL CHECK(length(name) BETWEEN 1 AND 255), declared_mime text NOT NULL, state file_state NOT NULL DEFAULT 'PROCESSING', favorite boolean NOT NULL DEFAULT false, expires_at timestamptz, deleted_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX files_owner_folder ON files(owner_id,folder_id,created_at DESC);
CREATE INDEX files_object ON files(object_id);
CREATE INDEX files_expiry ON files(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX files_name_search ON files USING gin(to_tsvector('simple',name));
CREATE TABLE uploads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES users(id), file_id uuid NOT NULL REFERENCES files(id), object_id uuid NOT NULL REFERENCES file_objects(id), fingerprint text NOT NULL, size bigint NOT NULL CHECK(size>0), part_size bigint NOT NULL, state upload_state NOT NULL DEFAULT 'CREATED', bytes_confirmed bigint NOT NULL DEFAULT 0, failure_count integer NOT NULL DEFAULT 0, ip text, error_code text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), expires_at timestamptz NOT NULL);
CREATE INDEX uploads_owner_state ON uploads(owner_id,state);
CREATE INDEX uploads_expiry ON uploads(expires_at);
CREATE TABLE multipart_sessions(upload_id uuid PRIMARY KEY REFERENCES uploads(id) ON DELETE CASCADE, storage_upload_id text NOT NULL UNIQUE);
CREATE TABLE upload_parts(upload_id uuid NOT NULL REFERENCES uploads(id) ON DELETE CASCADE, part_number integer NOT NULL CHECK(part_number BETWEEN 1 AND 10000), expected_bytes bigint NOT NULL, checksum_sha256 text NOT NULL, etag text, confirmed_at timestamptz, PRIMARY KEY(upload_id,part_number));
CREATE TABLE shares(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES users(id), slug text NOT NULL UNIQUE, name text NOT NULL, visibility text NOT NULL DEFAULT 'PUBLIC' CHECK(visibility IN ('PUBLIC','PRIVATE')), password_hash text, enabled boolean NOT NULL DEFAULT true, expires_at timestamptz, max_downloads integer CHECK(max_downloads>0), download_count bigint NOT NULL DEFAULT 0, view_count bigint NOT NULL DEFAULT 0, version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX shares_owner ON shares(owner_id);
CREATE TABLE share_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), share_id uuid NOT NULL REFERENCES shares(id) ON DELETE CASCADE, file_id uuid REFERENCES files(id), folder_id uuid REFERENCES folders(id), CHECK((file_id IS NULL)<>(folder_id IS NULL)));
CREATE INDEX share_items_share ON share_items(share_id);
CREATE TABLE share_access(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), share_id uuid NOT NULL REFERENCES shares(id) ON DELETE CASCADE, token_hash text NOT NULL UNIQUE, version integer NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE downloads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), file_id uuid NOT NULL REFERENCES files(id), share_id uuid REFERENCES shares(id), owner_id uuid NOT NULL REFERENCES users(id), bytes_authorized bigint NOT NULL, ip text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX downloads_owner_date ON downloads(owner_id,created_at);
CREATE TABLE storage_usage(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, used_bytes bigint NOT NULL, free_bytes bigint NOT NULL, total_bytes bigint NOT NULL, active_uploads integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE quotas(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), role user_role REFERENCES roles(name), policy jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), CHECK((user_id IS NULL)<>(role IS NULL)));
CREATE TABLE api_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), owner_id uuid NOT NULL REFERENCES users(id), name text NOT NULL, token_hash text NOT NULL UNIQUE, prefix text NOT NULL, scopes text[] NOT NULL, expires_at timestamptz, revoked_at timestamptz, last_used_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX api_keys_owner ON api_keys(owner_id);
CREATE TABLE settings(id integer PRIMARY KEY CHECK(id=1), value jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO settings VALUES (1,'{}');
CREATE TABLE audit_logs(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor_id uuid REFERENCES users(id), action text NOT NULL, target text, detail jsonb NOT NULL DEFAULT '{}', ip text, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX audit_logs_created ON audit_logs(created_at DESC);
CREATE INDEX audit_logs_actor ON audit_logs(actor_id,created_at DESC);
CREATE TABLE security_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, kind text NOT NULL, ip text, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ip_blocks(ip text PRIMARY KEY, reason text NOT NULL, actor_id uuid REFERENCES users(id), expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE abuse_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), share_id uuid REFERENCES shares(id), reason text NOT NULL, status text NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','RESOLVED','REJECTED')), decision text, actor_id uuid REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE background_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), kind text NOT NULL, target text, status text NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','RUNNING','COMPLETED','FAILED')), attempts integer NOT NULL DEFAULT 0, error text, detail jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(kind,target));
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id), kind text NOT NULL, message text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
