import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
test('CMS draft publication, support replies, SEO controls and plan editor work in the browser',async({page})=>{
 const owner=JSON.parse(await readFile(process.env.TEST_OWNER_FILE??'.secrets/owner-account.json','utf8'));
 await page.goto('/login');await page.getByLabel('Email address').fill(owner.email);await page.getByLabel('Password',{exact:true}).fill(owner.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page).toHaveURL(/\/drive/);
 const slug=`browser-check-${Date.now()}`;
 await page.goto('/admin/pages');await page.getByRole('button',{name:'New page',exact:true}).click();await page.getByLabel('URL slug',{exact:true}).fill(slug);await page.getByLabel('Title',{exact:true}).fill('Browser publication check');await page.getByRole('textbox',{name:'Page content',exact:true}).fill('This page was published using the real browser editor.');await page.getByRole('button',{name:'Publish',exact:true}).click();await expect(page.getByText('Changes saved',{exact:true})).toBeVisible();
 await page.goto('/en/'+slug);await expect(page.getByRole('heading',{name:'Browser publication check'})).toBeVisible();await expect(page.getByText('This page was published using the real browser editor.')).toBeVisible();
 await page.goto('/admin/pages');await page.locator('.settings-nav').getByRole('button',{name:/Browser publication check/}).click();await page.getByRole('button',{name:'Unpublish',exact:true}).click();await expect(page.getByText('Changes saved',{exact:true})).toBeVisible();
 await page.goto('/admin/seo');await expect(page.getByRole('heading',{name:'Search preview',exact:true})).toBeVisible();await expect(page.getByLabel('Enable optional tracking after visitor consent')).toBeDisabled();await expect(page.locator('a[href="/sitemap.xml"]')).toBeVisible();
 await page.goto('/admin/plans');await page.locator('.account-section').filter({has:page.getByRole('heading',{name:'Free',exact:true})}).getByRole('button',{name:'Settings',exact:true}).click();await expect(page.getByLabel('Concurrent download grants',{exact:true})).toHaveValue('8');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByText('Changes saved',{exact:true})).toBeVisible();
 const subject='Browser support '+Date.now();await page.goto('/support');await page.getByLabel('Subject',{exact:true}).fill(subject);await page.getByLabel('Message',{exact:true}).fill('Please verify this private support workflow.');await page.getByRole('button',{name:'Create support ticket',exact:true}).click();await expect(page.getByRole('heading',{name:subject})).toBeVisible();const ticketPath=new URL(page.url()).pathname;
 await page.goto('/admin/support');await page.getByRole('link',{name:subject,exact:true}).click();await page.getByLabel('Reply',{exact:true}).fill('Visible staff response');await page.getByRole('button',{name:'Send reply',exact:true}).click();await expect(page.getByText('Visible staff response',{exact:true})).toBeVisible();await page.getByLabel('Internal note',{exact:true}).check();await page.getByLabel('Reply',{exact:true}).fill('Staff-only browser note');await page.getByRole('button',{name:'Send reply',exact:true}).click();await expect(page.getByText('Staff-only browser note',{exact:true})).toBeVisible();
 await page.goto(ticketPath);await expect(page.getByText('Visible staff response',{exact:true})).toBeVisible();await expect(page.getByText('Staff-only browser note',{exact:true})).toHaveCount(0);
 await page.goto('/account/devices');await page.getByRole('button',{name:'Rename',exact:true}).first().click();await page.getByLabel('Device name',{exact:true}).fill('Browser acceptance device');await page.getByRole('dialog').getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByText('Browser acceptance device',{exact:true})).toBeVisible();
});
