import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {owner,Client,report} from './helpers.js';
import {one,query,pool} from '../packages/database/index.js';
const admin=await owner(),saved=(await admin.request('/admin/settings')).settings,checks:string[]=[];
const created:string[]=[];
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.info('PASS',name);}
async function upload(body:Buffer){const row=await admin.request('/uploads','POST',{name:`cloud-${Date.now()}-${randomBytes(3).toString('hex')}.bin`,size:body.length,mime:'application/octet-stream',fingerprint:createHash('sha256').update(body).digest('hex')});const signed=await admin.request(`/uploads/${row.id}/sign`,'POST',{parts:[{number:1,checksum:createHash('sha256').update(body).digest('base64')}]});assert.equal((await fetch(signed.parts[0].url,{method:'PUT',headers:signed.parts[0].headers,body:body as unknown as BodyInit})).status,200);const result=await admin.request(`/uploads/${row.id}/complete`,'POST',{});created.push(result.fileId);return (await admin.request(`/files/${result.fileId}`)).file;}
try{
 const first=randomBytes(12345),second=randomBytes(23456);let target:any,source:any,version:any;
 await check('Account change feed is ordered and paginated without cross-account data',async()=>{const folder=await admin.request('/folders','POST',{name:'Cloud cursor acceptance'});await admin.request(`/folders/${folder.id}`,'PATCH',{name:'Cloud cursor updated'});let cursor=0;const sequences:number[]=[];for(;;){const page=await admin.request(`/cloud/changes?cursor=${cursor}&limit=2`);for(const item of page.items){assert.ok(item.sequence>cursor);sequences.push(item.sequence);}cursor=page.cursor;if(!page.hasMore)break;}assert.ok(sequences.length>=2);assert.equal(new Set(sequences).size,sequences.length);const visitor=new Client();await visitor.request('/auth/guest','POST',{});assert.equal((await visitor.request('/cloud/changes')).items.length,0);await admin.request(`/cloud/changes?cursor=${Number.MAX_SAFE_INTEGER}`,'GET',undefined,409);});
 await check('Replacing a cloud file retains its original object and increases revision',async()=>{target=await upload(first);source=await upload(second);const result=await admin.request(`/files/${target.id}/versions`,'POST',{sourceFileId:source.id,expectedRevision:target.revision});assert.ok(result.revision>target.revision);const history=await admin.request(`/files/${target.id}/versions`);assert.equal(history.items.length,1);version=history.items[0];assert.equal(version.size,first.length);target=(await admin.request(`/files/${target.id}`)).file;const grant=await admin.request(`/files/${target.id}/download`,'POST',{});assert.deepEqual(Buffer.from(await(await fetch(grant.url)).arrayBuffer()),second);});
 await check('Stale edits and simultaneous restores cannot overwrite a newer revision',async()=>{await admin.request(`/files/${target.id}`,'PATCH',{name:'Stale rename',expectedRevision:target.revision-1},409);const results=await Promise.allSettled([1,2].map(()=>admin.request(`/files/${target.id}/versions/restore`,'POST',{versionId:version.id,expectedRevision:target.revision})));assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const grant=await admin.request(`/files/${target.id}/download`,'POST',{});assert.deepEqual(Buffer.from(await(await fetch(grant.url)).arrayBuffer()),first);});
 await check('Version retention obeys configured count and disabled-history policy',async()=>{await admin.request('/admin/settings','PUT',{...saved,maxVersionCount:1});target=(await admin.request(`/files/${target.id}`)).file;await admin.request(`/files/${target.id}/versions`,'POST',{sourceFileId:source.id,expectedRevision:target.revision});assert.equal((await admin.request(`/files/${target.id}/versions`)).items.length,1);await admin.request('/admin/settings','PUT',{...saved,versioningEnabled:false});const history=await admin.request(`/files/${target.id}/versions`);await admin.request(`/files/${target.id}/versions/restore`,'POST',{versionId:history.items[0].id,expectedRevision:history.file.revision},403);await admin.request('/admin/settings','PUT',{...saved,maxVersionDays:0});await admin.request('/admin/jobs','POST',{kind:'cleanup'});for(let attempt=0;attempt<40;attempt++){if((await admin.request(`/files/${target.id}/versions`)).items.length===0)break;await new Promise(r=>setTimeout(r,250));}assert.equal((await admin.request(`/files/${target.id}/versions`)).items.length,0);});
 await report('cloud-versions',{at:new Date().toISOString(),checks,passed:checks.length});
}finally{await admin.request('/admin/settings','PUT',saved);for(const id of created){await admin.request('/files/bulk','POST',{ids:[id],action:'delete'});await admin.request('/files/bulk','POST',{ids:[id],action:'purge',confirm:'DELETE PERMANENTLY'});}await pool.end();}
