import assert from 'node:assert/strict';
import {owner,Client,origin,report} from './helpers.js';
import {one,query,pool} from '../packages/database/index.js';
const admin=await owner(),checks:string[]=[];
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.info('PASS',name);}
let pageId:string|undefined;
try{
 await check('All bilingual legal pages are published from the database',async()=>{const pages=(await new Client().request('/pages')).items;assert.ok(pages.length>=8);for(const slug of ['terms','privacy','about','contact','acceptable-use','abuse','copyright'])for(const lang of ['en','ar']){const page=await new Client().request(`/pages/${slug}?lang=${lang}`);assert.ok(page.title&&page.html.length>100);}});
 const slug=`acceptance-${Date.now()}`,content={en:{title:'Content acceptance',html:'<h2>Safe heading</h2><p onclick="alert(1)">Safe text<script>alert(1)</script><img src=x onerror=alert(1)><a href="javascript:alert(1)">bad</a></p>',description:'An actual description for the content acceptance page.'},ar:{title:'اختبار المحتوى',html:'<p>محتوى عربي آمن للاختبار.</p>',description:'وصف عربي لصفحة اختبار المحتوى.'},indexable:true};
 await check('Draft CMS content is sanitized and cannot be retrieved publicly',async()=>{pageId=(await admin.request('/admin/pages','POST',{slug,content,publish:false})).id;await new Client().request(`/pages/${slug}`,'GET',undefined,404);const detail=await admin.request(`/admin/pages/${pageId}`);assert.doesNotMatch(detail.page.draft.en.html,/script|onclick|onerror|javascript:/);});
 await check('Published pages have localized server-rendered metadata and safe content',async()=>{const detail=await admin.request(`/admin/pages/${pageId}`);await admin.request(`/admin/pages/${pageId}`,'PUT',{slug,kind:'page',content:detail.page.draft,publish:true,expectedRevision:detail.page.revision});for(const lang of ['en','ar']){const response=await fetch(`${origin}/${lang}/${slug}`);assert.equal(response.status,200);const html=await response.text();assert.ok(html.includes(`lang="${lang}"`));assert.ok(html.includes('hreflang="x-default"'));assert.ok(html.includes('rel="canonical"'));assert.ok(html.includes('application/ld+json'));assert.doesNotMatch(html,/onclick="alert|onerror=alert|javascript:alert/);}});
 await check('Draft edits and revision restoration preserve the published version',async()=>{const before=await admin.request(`/admin/pages/${pageId}`);await admin.request(`/admin/pages/${pageId}`,'PUT',{slug,kind:'page',content:{...before.page.draft,en:{...before.page.draft.en,title:'Draft only title'}},expectedRevision:before.page.revision});assert.equal((await new Client().request(`/pages/${slug}`)).title,'Content acceptance');const edited=await admin.request(`/admin/pages/${pageId}`);await admin.request(`/admin/pages/${pageId}/restore`,'POST',{revisionId:edited.revisions.at(-1).id,expectedRevision:edited.page.revision});assert.equal((await admin.request(`/admin/pages/${pageId}`)).page.draft.en.title,'Content acceptance');await admin.request(`/admin/pages/${pageId}/restore`,'POST',{revisionId:edited.revisions.at(-1).id,expectedRevision:edited.page.revision},409);});
 await check('Robots and sitemap exclude all private file, share, and support routes',async()=>{const robots=await(await fetch(origin+'/robots.txt')).text();for(const route of ['/admin','/account','/drive','/api','/s/','/support'])assert.ok(robots.includes(`Disallow: ${route}`));const sitemap=await(await fetch(origin+'/sitemap.xml')).text();assert.ok(sitemap.includes('/ar/privacy')&&sitemap.includes('/en/privacy'));assert.doesNotMatch(sitemap,/\/(admin|account|drive|support|s)\//);assert.ok(sitemap.includes(slug));});
 await check('Global SEO settings validate IDs and produce actionable audit results',async()=>{const before=await admin.request('/admin/seo');assert.equal(before.settings.trackingEnabled,false);await admin.request('/admin/seo','PUT',{settings:{...before.settings,analyticsId:'<script>bad</script>'},expectedRevision:before.revision},400);await admin.request('/admin/seo','PUT',{settings:{...before.settings,googleVerification:'AstraFileAcceptance'},expectedRevision:before.revision});const page=await new Client().request('/pages/privacy?lang=ar');assert.equal(page.meta.googleVerification,'AstraFileAcceptance');const after=await admin.request('/admin/seo');await admin.request('/admin/seo','PUT',{settings:before.settings,expectedRevision:after.revision});});
 let ticket:any,secret:string,visitor=new Client();
 await check('Anonymous support creates a digest-only capability without personal details',async()=>{ticket=await visitor.request('/support/tickets','POST',{category:'TECHNICAL',subject:'Encrypted subject acceptance',message:'Private support message acceptance.'});secret=new URL(ticket.url).hash.slice(1);assert.equal(Buffer.from(secret,'base64url').length,32);const row=await one('SELECT * FROM support_tickets WHERE id=$1',[ticket.id]);assert.equal(row!.owner_id,null);assert.equal(JSON.stringify(row).includes(secret),false);assert.equal(JSON.stringify(row).includes('Encrypted subject acceptance'),false);const messages=await query('SELECT * FROM support_messages WHERE ticket_id=$1',[ticket.id]);assert.equal(JSON.stringify(messages).includes('Private support message acceptance'),false);await new Client().request(`/support/tickets/${ticket.id}`,'GET',undefined,404);await visitor.request('/support/resolve','POST',{secret});assert.equal((await visitor.request(`/support/tickets/${ticket.id}`)).ticket.subject,'Encrypted subject acceptance');});
 await check('Support replies, private notes, assignment, close and reopen work without SMTP',async()=>{const me=(await admin.request('/auth/me')).user;await admin.request(`/admin/support/${ticket.id}`,'PATCH',{status:'IN_PROGRESS',assigneeId:me.id});await admin.request(`/admin/support/${ticket.id}/messages`,'POST',{body:'Private staff-only note.',internal:true});await admin.request(`/admin/support/${ticket.id}/messages`,'POST',{body:'A reply visible to the requester.',internal:false});const view=await visitor.request(`/support/tickets/${ticket.id}`);assert.equal(view.messages.length,2);assert.equal(JSON.stringify(view).includes('Private staff-only note'),false);await visitor.request(`/support/tickets/${ticket.id}/messages`,'POST',{body:'Requester follow-up.'});await admin.request(`/admin/support/${ticket.id}`,'PATCH',{status:'CLOSED'});await visitor.request(`/support/tickets/${ticket.id}/messages`,'POST',{body:'Closed reply.'},409);await admin.request(`/admin/support/${ticket.id}`,'PATCH',{status:'OPEN'});await visitor.request(`/support/tickets/${ticket.id}/messages`,'POST',{body:'Reopened reply.'});const result=await admin.request('/admin/support?q=Encrypted%20subject');assert.ok(result.items.some((row:any)=>row.id===ticket.id));assert.equal(JSON.stringify(await admin.request(`/admin/support/${ticket.id}`)).includes(secret),false);});
 await check('Signed-in support uses account identity and hides tickets from other accounts',async()=>{const created=await admin.request('/support/tickets','POST',{category:'ACCOUNT',subject:'Account-associated support',message:'Account-linked request without storing email.'});assert.equal(created.url,undefined);await admin.request(`/support/tickets/${created.id}`);await visitor.request(`/support/tickets/${created.id}`,'GET',undefined,404);});
 await report('content-support',{at:new Date().toISOString(),checks,passed:checks.length});
}finally{if(pageId){const detail=await admin.request(`/admin/pages/${pageId}`);await admin.request(`/admin/pages/${pageId}`,'PUT',{slug:detail.page.slug,kind:detail.page.kind,content:detail.page.draft,publish:false,expectedRevision:detail.page.revision});}await pool.end();}
