import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {GetObjectCommand} from '@aws-sdk/client-s3';
import {getSignedUrl} from '@aws-sdk/s3-request-presigner';
import {Client,owner,origin,report} from './helpers.js';
import {s3,storage} from '../packages/storage/index.js';
import {pool,one,query} from '../packages/database/index.js';
import {env} from '../packages/config/index.js';
const checks:string[]=[];const admin=await owner();const files:any[]=[];
async function check(name:string,run:()=>Promise<void>){await run();checks.push(name);console.info('PASS',name);}
async function until(fn:()=>Promise<boolean>){for(let n=0;n<120;n++){if(await fn())return;await new Promise(r=>setTimeout(r,500));}throw Error('Background operation did not complete');}
async function upload(bytes:Buffer,name:string){const u=await admin.request('/uploads','POST',{name,size:bytes.length,mime:'application/octet-stream',fingerprint:createHash('sha256').update(bytes).digest('hex')});for(let n=1;n<=u.partCount;n++){const body=bytes.subarray((n-1)*u.partSize,n*u.partSize),checksum=createHash('sha256').update(body).digest('base64');const s=await admin.request(`/uploads/${u.id}/sign`,'POST',{parts:[{number:n,checksum}]});const r=await fetch(s.parts[0].url,{method:'PUT',headers:s.parts[0].headers,body:body as unknown as BodyInit});assert.equal(r.status,200);await admin.request(`/uploads/${u.id}/ack`,'POST',{number:n,etag:r.headers.get('etag')});}const done=await admin.request(`/uploads/${u.id}/complete`,'POST',{});const f=await one('SELECT f.*,o.object_key FROM files f JOIN file_objects o ON o.id=f.object_id WHERE f.id=$1',[done.fileId]);files.push(f);return f!;}
try{
 let maxHealthMs=0,maxApiRss=0,running=true;const monitor=(async()=>{while(running){const start=performance.now();const h=await fetch(origin+'/health/ready');assert.equal(h.status,200);maxHealthMs=Math.max(maxHealthMs,performance.now()-start);const o=await admin.request('/admin/overview');maxApiRss=Math.max(maxApiRss,o.system.apiMemory);await new Promise(r=>setTimeout(r,300));}})();
 const bodies=[randomBytes(130*1024**2),randomBytes(130*1024**2),randomBytes(130*1024**2)];
 const started=performance.now();
 try{await check('Three simultaneous multipart uploads/downloads preserve independent SHA-256',async()=>{await Promise.all(bodies.map(async(b,n)=>{const f=await upload(b,`concurrent-${n}-${Date.now()}.bin`);const grant=await admin.request(`/files/${f.id}/download`,'POST',{});const response=await fetch(grant.url);assert.equal(response.status,200);const h=createHash('sha256');for await(const chunk of response.body!)h.update(chunk);assert.equal(h.digest('hex'),createHash('sha256').update(b).digest('hex'));}));});}finally{running=false;await monitor;}
 const seconds=(performance.now()-started)/1000;assert.ok(maxApiRss<512*1024**2,'API exceeded memory budget');assert.ok(maxHealthMs<3000,'Control plane health became unresponsive');
 const f=files[0];
 await check('Anonymous bucket/object access is denied; expired signed URLs are rejected',async()=>{for(const url of [`${env.S3_PUBLIC_ENDPOINT}/${env.S3_BUCKET}`,`${env.S3_PUBLIC_ENDPOINT}/${env.S3_BUCKET}/${f.object_key}`]){const r=await fetch(url);assert.ok([401,403].includes(r.status));await r.arrayBuffer();}const expired=await getSignedUrl(s3,new GetObjectCommand({Bucket:env.S3_BUCKET,Key:f.object_key}),{expiresIn:1,signingDate:new Date(Date.now()-60000)});const r=await fetch(expired);assert.equal(r.status,403);await r.arrayBuffer();});
 await check('Share password brute force is rate limited',async()=>{const share=await admin.request('/shares','POST',{name:'Rate verification',fileIds:[f.id],password:'test-share-password'});const visitor=new Client();const resolved=await visitor.request('/shares/resolve','POST',{secret:new URL(share.url).hash.slice(1)});for(let n=0;n<8;n++)await visitor.request(`/public/shares/${resolved.shareId}/unlock`,'POST',{password:'incorrect'},403);await visitor.request(`/public/shares/${resolved.shareId}/unlock`,'POST',{password:'incorrect'},429);await admin.request(`/shares/${share.id}`,'DELETE');});
 await check('Deleted ancestor hides file metadata in an existing public share',async()=>{const a=await admin.request('/folders','POST',{name:'Hidden ancestor'}),b=await admin.request('/folders','POST',{name:'Nested',parentId:a.id});await admin.request(`/files/${f.id}`,'PATCH',{folderId:b.id});const share=await admin.request('/shares','POST',{name:'Hidden metadata',fileIds:[f.id]});await admin.request(`/folders/${a.id}`,'PATCH',{deleted:true});const visitor=new Client();const resolved=await visitor.request('/shares/resolve','POST',{secret:new URL(share.url).hash.slice(1)});const response=await visitor.request(`/public/shares/${resolved.shareId}`);assert.equal(response.files.length,0);await admin.request(`/folders/${a.id}`,'PATCH',{deleted:false});});
 await check('Concurrent quota admission cannot overbook an account',async()=>{const guest=new Client();await guest.request('/auth/guest','POST',{});const u=(await guest.request('/auth/me')).user;await admin.request(`/admin/users/${u.id}`,'PATCH',{quota:{storageBytes:100,fileBytes:100}});const outcomes=await Promise.allSettled([1,2].map(n=>guest.request('/uploads','POST',{name:`quota-${n}.bin`,size:75,mime:'application/octet-stream',fingerprint:'0'.repeat(64)})));assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);for(const r of outcomes)if(r.status==='fulfilled')await guest.request(`/uploads/${r.value.id}/abort`,'POST',{});});
 await check('Anonymous-disabled, read-only, oversized control requests, and metrics protection',async()=>{const {settings}=await admin.request('/admin/settings');try{await admin.request('/admin/settings','PUT',{...settings,anonymousEnabled:false});await new Client().request('/auth/guest','POST',{},403);await admin.request('/admin/settings','PUT',{...settings,readOnly:true});await admin.request('/uploads','POST',{name:'read-only.bin',size:1,mime:'application/octet-stream',fingerprint:'0'.repeat(64)},503);}finally{await admin.request('/admin/settings','PUT',settings);}const r=await fetch(origin+'/api/auth/guest',{method:'POST',headers:{origin,'x-astra-client':'web','content-type':'application/json'},body:JSON.stringify({large:'a'.repeat(150*1024)})});assert.equal(r.status,413);await new Client().request('/admin/metrics','GET',undefined,401);const res=await fetch(origin+'/api/admin/metrics',{headers:{cookie:[...admin.cookies].map(([k,v])=>`${k}=${v}`).join('; ')}});assert.equal(res.status,200);assert.match(await res.text(),/astrafile_api_requests_total/);});
 await check('Worker SHA-256 matches original bytes',async()=>{await until(async()=>!!(await one('SELECT sha256 FROM file_objects WHERE id=$1',[f.object_id]))?.sha256);const row=await one('SELECT sha256 FROM file_objects WHERE id=$1',[f.object_id]);const index=Number(f.name.split('-')[1]);assert.equal(row!.sha256,createHash('sha256').update(bodies[index]).digest('hex'));});
 await check('Expiration worker denies access and purges only the expired object',async()=>{const target=files[1];await admin.request(`/files/${target.id}`,'PATCH',{expiresAt:new Date(Date.now()-1000).toISOString()});await admin.request(`/files/${target.id}/download`,'POST',{},404);await admin.request('/admin/jobs','POST',{kind:'cleanup'});await until(async()=>(await one('SELECT state FROM file_objects WHERE id=$1',[target.object_id]))?.state==='PURGED');await assert.rejects(storage.head(target.object_key));assert.ok((await storage.head(f.object_key)).size>0);});
 await check('Admin-triggered metadata backup completes successfully',async()=>{await admin.request('/admin/jobs','POST',{kind:'backup'});await until(async()=>(await one("SELECT status FROM background_jobs WHERE kind='backup' AND target='manual'"))?.status==='COMPLETED');const job=await one("SELECT detail FROM background_jobs WHERE kind='backup' AND target='manual'");assert.ok(job!.detail.bytes>100);});
 await report('extended',{date:new Date().toISOString(),checks,concurrentFiles:3,concurrentBytes:3*130*1024**2,seconds,maxHealthMs,apiPeakRssMiB:maxApiRss/1024**2});
}finally{for(const f of files){const row=await one('SELECT state FROM files WHERE id=$1',[f.id]);if(row?.state==='AVAILABLE'){await admin.request('/files/bulk','POST',{ids:[f.id],action:'delete'});await admin.request('/files/bulk','POST',{ids:[f.id],action:'purge',confirm:'DELETE PERMANENTLY'});}}await pool.end();s3.destroy();}
