import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {Client,owner,report} from './helpers.js';
import {one,query,pool} from '../packages/database/index.js';
import {storage} from '../packages/storage/index.js';
const admin=await owner(),saved=(await admin.request('/admin/settings')).settings,checks:string[]=[];
const created:string[]=[];async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.info('PASS',name);}
async function account(){const c=new Client(),password=randomBytes(24).toString('base64url');await c.request('/auth/register','POST',{email:`hardening-${randomBytes(10).toString('hex')}@astrafile.local`,password});const user=(await c.request('/auth/me')).user;await c.request('/auth/password','POST',{current:password,password:password+'x'});await admin.request(`/admin/users/${user.id}`,'PATCH',{status:'ACTIVE'});return {c,user};}
const payload=()=>({name:'hardening-owned-fixture.bin',size:1024,mime:'application/octet-stream',fingerprint:randomBytes(32).toString('hex')});
try{
 await admin.request('/admin/settings','PUT',{...saved,registrationEnabled:true,requireManualActivation:true});
 const {c,user}=await account();
 await check('Pending account changes password; activation preserves identity',async()=>assert.equal((await c.request('/auth/me')).user.accountId,user.accountId));
 await check('Upload creation flood is rejected before allocating more storage',async()=>{await admin.request('/admin/settings','PUT',{...saved,uploadCreatesPerMinute:2});for(let n=0;n<2;n++){const u=await c.request('/uploads','POST',payload());created.push(u.id);await c.request(`/uploads/${u.id}/abort`,'POST',{});}assert.equal((await c.request('/uploads','POST',payload(),429)).code,'RATE_LIMITED');assert.equal((await c.request('/files/usage')).reserved_bytes,0);await admin.request('/admin/settings','PUT',saved);});
 const second=await account();
 await check('Fake acknowledgements cannot complete an object or refund its reservation',async()=>{const u=await second.c.request('/uploads','POST',payload());created.push(u.id);await second.c.request(`/uploads/${u.id}/sign`,'POST',{parts:[{number:1,checksum:createHash('sha256').update(Buffer.alloc(1024)).digest('base64')}]});await second.c.request(`/uploads/${u.id}/ack`,'POST',{number:1,etag:'fabricated'});await second.c.request(`/uploads/${u.id}/complete`,'POST',{},409);assert.equal((await second.c.request('/files/usage')).reserved_bytes,1024);await second.c.request(`/uploads/${u.id}/abort`,'POST',{});});
 await check('Repeated invalid completion triggers creation cooldown while resume remains available',async()=>{await admin.request('/admin/settings','PUT',{...saved,failedUploadThreshold:2});const u=await second.c.request('/uploads','POST',payload());created.push(u.id);await second.c.request(`/uploads/${u.id}/complete`,'POST',{},409);await second.c.request(`/uploads/${u.id}/complete`,'POST',{},409);assert.equal((await second.c.request('/uploads','POST',payload(),429)).code,'UPLOAD_COOLDOWN');await second.c.request(`/uploads/${u.id}`);await second.c.request(`/uploads/${u.id}/abort`,'POST',{});await admin.request('/admin/settings','PUT',saved);});
 const third=await account();
 await check('Abandoned multipart cleanup removes storage session and releases exact reservation',async()=>{const u=await third.c.request('/uploads','POST',payload());created.push(u.id);const stored=(await one('SELECT o.object_key,m.storage_upload_id FROM uploads u JOIN file_objects o ON o.id=u.object_id JOIN multipart_sessions m ON m.upload_id=u.id WHERE u.id=$1',[u.id]))!;await query("UPDATE uploads SET expires_at=now()-interval '1 minute' WHERE id=$1",[u.id]);await admin.request('/admin/jobs','POST',{kind:'cleanup'});for(let n=0;n<80;n++){if((await one('SELECT state FROM uploads WHERE id=$1',[u.id]))!.state==='EXPIRED')break;await new Promise(r=>setTimeout(r,250));}assert.equal((await one('SELECT state FROM uploads WHERE id=$1',[u.id]))!.state,'EXPIRED');assert.equal((await third.c.request('/files/usage')).reserved_bytes,0);let found=false;for await(const item of storage.multipart())if(item.UploadId===stored.storage_upload_id)found=true;assert.equal(found,false);});
 await check('Critical disk floor blocks allocation without consuming logical quota',async()=>{await admin.request('/admin/settings','PUT',{...saved,criticalFreeGiB:100000});assert.equal((await third.c.request('/uploads','POST',payload(),507)).code,'LOW_DISK');assert.equal((await third.c.request('/files/usage')).reserved_bytes,0);await admin.request('/admin/settings','PUT',saved);});
 await check('Download grants obey an atomic per-owner limit',async()=>{const body=Buffer.alloc(1024),u=await third.c.request('/uploads','POST',payload());created.push(u.id);const sign=await third.c.request(`/uploads/${u.id}/sign`,'POST',{parts:[{number:1,checksum:createHash('sha256').update(body).digest('base64')}]});assert.equal((await fetch(sign.parts[0].url,{method:'PUT',headers:sign.parts[0].headers,body})).status,200);const file=await third.c.request(`/uploads/${u.id}/complete`,'POST',{});await admin.request(`/admin/users/${third.user.id}`,'PATCH',{quota:{concurrentDownloads:1}});const results=await Promise.allSettled([third.c.request(`/files/${file.fileId}/download`,'POST',{}),third.c.request(`/files/${file.fileId}/download`,'POST',{})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await third.c.request(`/files/${file.fileId}/download`,'POST',{},429)).code,'DOWNLOAD_CONCURRENCY');await third.c.request('/files/bulk','POST',{ids:[file.fileId],action:'delete'});await third.c.request('/files/bulk','POST',{ids:[file.fileId],action:'purge',confirm:'DELETE PERMANENTLY'});});
 await report('hardening-acceptance',{at:new Date().toISOString(),checks,passed:checks.length});
}finally{await admin.request('/admin/settings','PUT',saved);await pool.end();}
