import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {owner,Client,origin,report} from './helpers.js';
const checks:{name:string;passed:boolean;ms:number}[]=[];
async function check(name:string,fn:()=>Promise<void>){const started=performance.now();await fn();checks.push({name,passed:true,ms:Math.round(performance.now()-started)});console.info('PASS',name);}
const admin=await owner();const guest=new Client(),intruder=new Client();await guest.request('/auth/guest','POST',{});await intruder.request('/auth/guest','POST',{});
const size=64*1024**2+1024**2+17;const bytes=randomBytes(size);const digest=createHash('sha256').update(bytes).digest('hex');const fingerprint=createHash('sha256').update('integration'+Date.now()).digest('hex');let upload:any,completed:any,share:any;
await check('CSRF rejection',async()=>{const res=await fetch(`${origin}/api/auth/guest`,{method:'POST',headers:{'content-type':'application/json'},body:'{}'});assert.equal(res.status,403);});
await check('Anonymous multipart initialization and cross-user isolation',async()=>{upload=await guest.request('/uploads','POST',{name:'أرشيف الاختبار.bin',size,mime:'application/octet-stream',fingerprint});assert.equal(upload.partCount,2);await intruder.request(`/uploads/${upload.id}`,'GET',undefined,404);await intruder.request(`/files/${upload.fileId}`,'GET',undefined,404);});
await check('Invalid part and MIME validation',async()=>{await guest.request(`/uploads/${upload.id}/sign`,'POST',{parts:[{number:3,checksum:'A'.repeat(43)+'='}]},400);await guest.request('/uploads','POST',{name:'../bad.bin',size:100,mime:'application/octet-stream',fingerprint},400);});
let firstEtag='';
async function put(n:number,body:Buffer){const checksum=createHash('sha256').update(body).digest('base64');const s=await guest.request(`/uploads/${upload.id}/sign`,'POST',{parts:[{number:n,checksum}]});const res=await fetch(s.parts[0].url,{method:'PUT',headers:s.parts[0].headers,body:body as unknown as BodyInit});if(!res.ok)throw Error(`Storage rejected part: HTTP ${res.status}: ${(await res.text()).replace(/<AccessKeyId>.*?<\/AccessKeyId>/g,'<redacted>')}`);const etag=res.headers.get('etag')!;assert.ok(etag);await guest.request(`/uploads/${upload.id}/ack`,'POST',{number:n,etag});return etag;}
await check('Storage validates SHA-256 and signed content length',async()=>{const body=bytes.subarray(0,upload.partSize);const checksum=createHash('sha256').update(body).digest('base64');const s=await guest.request(`/uploads/${upload.id}/sign`,'POST',{parts:[{number:1,checksum}]});const wrong=Buffer.alloc(body.length);const res=await fetch(s.parts[0].url,{method:'PUT',headers:s.parts[0].headers,body:wrong});assert.ok(res.status>=400,`Checksum mismatch accepted: ${res.status}`);await res.arrayBuffer();const short=await fetch(s.parts[0].url,{method:'PUT',headers:s.parts[0].headers,body:bytes.subarray(0,10)});assert.ok(short.status>=400,`Signed length mismatch accepted: ${short.status}`);await short.arrayBuffer();});
await check('Interrupted upload reuses existing confirmed part',async()=>{firstEtag=await put(1,bytes.subarray(0,upload.partSize));const state=await guest.request(`/uploads/${upload.id}`);assert.equal(state.parts.length,1);assert.equal(state.parts[0].etag,firstEtag);await guest.request(`/uploads/${upload.id}/complete`,'POST',{},409);await put(2,bytes.subarray(upload.partSize));const after=await guest.request(`/uploads/${upload.id}`);assert.equal(after.parts[0].etag,firstEtag);assert.equal(after.parts.length,2);});
await check('Complete only after object verification; idempotent completion',async()=>{completed=await guest.request(`/uploads/${upload.id}/complete`,'POST',{});assert.ok(completed.shareSecret);const again=await guest.request(`/uploads/${upload.id}/complete`,'POST',{});assert.equal(again.shareSecret,undefined);assert.equal(again.fileId,completed.fileId);const f=await guest.request(`/files/${completed.fileId}`);assert.equal(f.file.state,'AVAILABLE');assert.equal(f.file.size,size);});
await check('Direct download returns original bytes and Arabic filename',async()=>{const grant=await guest.request(`/files/${completed.fileId}/download`,'POST',{});const res=await fetch(grant.url);assert.equal(res.status,200);assert.equal(Number(res.headers.get('content-length')),size);assert.ok(res.headers.get('content-disposition')?.includes("filename*="));const result=createHash('sha256');for await(const chunk of res.body!)result.update(chunk);assert.equal(result.digest('hex'),digest);});
await check('Range download and partial resume',async()=>{const grant=await guest.request(`/files/${completed.fileId}/download`,'POST',{});const res=await fetch(grant.url,{headers:{Range:'bytes=1048576-2097151'}});assert.equal(res.status,206);assert.equal(res.headers.get('content-range'),`bytes 1048576-2097151/${size}`);assert.deepEqual(Buffer.from(await res.arrayBuffer()),bytes.subarray(1048576,2097152));});
await check('Password share, wrong password, counters, limit and revocation',async()=>{share=await guest.request('/shares','POST',{name:'Protected verification',fileIds:[completed.fileId],password:'safe-test-password-2026',maxDownloads:1});const visitor=new Client();const resolved=await visitor.request('/shares/resolve','POST',{secret:new URL(share.url).hash.slice(1)});share.shareId=resolved.shareId;await visitor.request(`/public/shares/${share.shareId}`,'GET',undefined,401);await visitor.request(`/public/shares/${share.shareId}/unlock`,'POST',{password:'incorrect'},403);await visitor.request(`/public/shares/${share.shareId}/unlock`,'POST',{password:'safe-test-password-2026'});const contents=await visitor.request(`/public/shares/${share.shareId}`);assert.equal(contents.files[0].id,completed.fileId);await visitor.request(`/public/shares/${share.shareId}/download`,'POST',{fileId:completed.fileId});await visitor.request(`/public/shares/${share.shareId}/download`,'POST',{fileId:completed.fileId},410);await guest.request(`/shares/${share.id}`,'PATCH',{enabled:false});await visitor.request(`/public/shares/${share.shareId}`,'GET',undefined,410);});
await check('Folder hierarchy, cycle prevention, copy, trash and restore',async()=>{const a=await guest.request('/folders','POST',{name:'المجلد الأول'}),b=await guest.request('/folders','POST',{name:'Nested',parentId:a.id});await guest.request(`/folders/${a.id}`,'PATCH',{parentId:b.id},400);await guest.request(`/files/${completed.fileId}`,'PATCH',{folderId:b.id});await guest.request('/files/bulk','POST',{ids:[completed.fileId],action:'copy',folderId:a.id});await guest.request('/files/bulk','POST',{ids:[completed.fileId],action:'delete'});await guest.request(`/files/${completed.fileId}/download`,'POST',{},404);await guest.request('/files/bulk','POST',{ids:[completed.fileId],action:'restore'});await guest.request(`/folders/${a.id}`,'PATCH',{deleted:true});await guest.request(`/files/${completed.fileId}/download`,'POST',{},404);await guest.request(`/folders/${a.id}`,'PATCH',{deleted:false});await guest.request(`/files/${completed.fileId}/download`,'POST',{});});
await check('Private share and expiration',async()=>{const p=await guest.request('/shares','POST',{name:'Private',fileIds:[completed.fileId],visibility:'PRIVATE'});await intruder.request('/shares/resolve','POST',{secret:new URL(p.url).hash.slice(1)},403);const resolved=await guest.request('/shares/resolve','POST',{secret:new URL(p.url).hash.slice(1)});await guest.request(`/public/shares/${resolved.shareId}`);await guest.request(`/shares/${p.id}`,'PATCH',{expiresAt:new Date(Date.now()+1100).toISOString()});await new Promise(resolve=>setTimeout(resolve,1200));await guest.request(`/public/shares/${resolved.shareId}`,'GET',undefined,410);});
await check('RBAC, final owner protection, user suspension, quotas, and API key revocation',async()=>{await guest.request('/admin/users','GET',undefined,403);const me=await admin.request('/auth/me');await admin.request(`/admin/users/${me.user.id}`,'PATCH',{status:'SUSPENDED'},409);const reg=new Client();await reg.request('/auth/register','POST',{email:`verify-${Date.now()}@astrafile.local`,name:'Verification user',password:'test-long-password-2026'});const u=(await reg.request('/auth/me')).user;await admin.request(`/admin/users/${u.id}`,'PATCH',{status:'ACTIVE',planId:'PRO'});const key=await reg.request('/keys','POST',{name:'Test key',scopes:['files:read']});const bearer=new Client();bearer.bearer=key.token;await bearer.request('/files');await bearer.request('/uploads','POST',{},403);const keys=await reg.request('/keys');await reg.request(`/keys/${keys.items[0].id}`,'DELETE');await bearer.request('/files','GET',undefined,401);await admin.request(`/admin/users/${u.id}`,'PATCH',{quota:{fileBytes:1024,storageBytes:1024,dailyBytes:1024,monthlyBytes:1024,bandwidthBytes:1024}});await reg.request('/uploads','POST',{name:'too-big.bin',size:2048,fingerprint,mime:'application/octet-stream'},413);await admin.request(`/admin/users/${u.id}`,'PATCH',{status:'SUSPENDED'});await reg.request('/files','GET',undefined,401);});
await check('All administration modules use real APIs',async()=>{for(const module of ['overview','files','uploads','shares','users','storage','security','jobs','audit','analytics','settings','api','health','reports','notifications','plans'])await admin.request(`/admin/${module}`);});
await check('Low-disk admission control',async()=>{const {settings}=await admin.request('/admin/settings');try{await admin.request('/admin/settings','PUT',{...settings,minimumFreeGiB:99999,warningFreeGiB:100000});await guest.request('/uploads','POST',{name:'lowdisk.bin',size:100,fingerprint,mime:'application/octet-stream'},507);}finally{await admin.request('/admin/settings','PUT',settings);}});
await report('integration',{date:new Date().toISOString(),checks,sourceSha256:digest,fileId:completed.fileId,bytes:size});console.info(`Integration verification passed: ${checks.length} checks.`);
