import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {owner,Client,report,origin} from './helpers.js';
import {one,query,pool} from '../packages/database/index.js';
import {emailLookups,blockReferences,networkReference} from '../packages/privacy/index.js';
const checks:string[]=[];
async function check(name:string,fn:()=>Promise<void>){await fn();checks.push(name);console.info('PASS',name);}
const admin=await owner(),settings=(await admin.request('/admin/settings')).settings;
const email=`privacy-${Date.now()}@astrafile.local`,password=randomBytes(24).toString('base64url'),client=new Client();
let user:any;const uploads:string[]=[];
try{
 await admin.request('/admin/settings','PUT',{...settings,registrationEnabled:true,requireManualActivation:true});
 await check('Registration creates a pending account with a random public ID',async()=>{const registered=await client.request('/auth/register','POST',{email,password});assert.equal(registered.status,'PENDING');user=(await client.request('/auth/me')).user;assert.match(user.accountId,/^AF-[A-F0-9]{32}$/);assert.equal(user.email,undefined);});
 await check('Email is a keyed blind index and passwords are Argon2id',async()=>{const record=(await one('SELECT * FROM users WHERE id=$1',[user.id]))!;assert.ok(emailLookups(email).includes(record.email_lookup));assert.match(record.password_hash,/^\$argon2id\$/);assert.equal(JSON.stringify(record).includes(email),false);assert.equal(record.email,undefined);assert.equal(record.name,user.accountId);});
 await check('Pending accounts cannot upload, share or use API keys',async()=>{await client.request('/uploads','POST',{name:'pending.bin',size:1,mime:'application/octet-stream',fingerprint:'a'.repeat(64)},403);await client.request('/shares','POST',{name:'Pending',fileIds:['00000000-0000-4000-8000-000000000000']},403);await client.request('/keys','POST',{name:'Pending',scopes:['files:read']},403);});
 await check('Account ID is immutable and cannot authenticate',async()=>{await assert.rejects(query('UPDATE users SET account_id=$2 WHERE id=$1',[user.id,'AF-'+randomBytes(16).toString('hex').toUpperCase()]));const anonymous=new Client();anonymous.bearer=user.accountId;await anonymous.request('/files','GET',undefined,401);});
 await check('Administrator lookup uses Account ID without email disclosure',async()=>{const result=await admin.request(`/admin/users?q=${user.accountId}`);assert.equal(result.items[0].id,user.id);assert.equal(JSON.stringify(result).includes(email),false);assert.equal(result.items[0].email_lookup,undefined);});
 await check('Manual activation allows the existing session to use My Cloud',async()=>{await admin.request(`/admin/users/${user.id}`,'PATCH',{status:'ACTIVE'});await client.request('/files');});
 await check('Free and Pro defaults and API entitlements are enforced',async()=>{const plans=(await admin.request('/admin/plans')).items;assert.equal(plans.find((p:any)=>p.id==='FREE').policy.storageBytes,200*1024**3);assert.equal(plans.find((p:any)=>p.id==='PRO').policy.storageBytes,2*1024**4);await client.request('/keys','POST',{name:'Excluded plan API',scopes:['files:read']},403);});
 await check('Independent overrides survive plan changes and explicit removal',async()=>{await admin.request(`/admin/users/${user.id}`,'PATCH',{quota:{storageBytes:3*1024**3,fileBytes:1024**3,concurrentUploads:1,shareCount:1}});await admin.request(`/admin/users/${user.id}`,'PATCH',{planId:'PRO'});const value=await client.request('/account/entitlements');assert.equal(value.effective.storageBytes,3*1024**3);assert.equal(value.effective.concurrentUploads,1);assert.equal(value.effective.apiEnabled,true);await admin.request(`/admin/users/${user.id}`,'PATCH',{quota:null});const reset=await client.request('/account/entitlements');assert.deepEqual(reset.override,{});assert.equal(reset.effective.storageBytes,2*1024**4);});
 await check('Plan editing accepts plan identifiers and updates real policy',async()=>{const value=(await admin.request('/admin/plans')).items.find((p:any)=>p.id==='FREE');await admin.request('/admin/plans/TEST_PRIVACY','PUT',{name:'Privacy acceptance',policy:{...value.policy,storageBytes:400*1024**3},enabled:true});await admin.request(`/admin/users/${user.id}`,'PATCH',{planId:'TEST_PRIVACY'});assert.equal((await client.request('/account/entitlements')).effective.storageBytes,400*1024**3);await admin.request(`/admin/users/${user.id}`,'PATCH',{planId:'FREE'});});
 await check('Multiple devices share account identity and hide raw client details',async()=>{const device=new Client();await device.request('/auth/login','POST',{email,password});assert.equal((await device.request('/auth/me')).user.accountId,user.accountId);const sessions=(await client.request('/auth/sessions')).items;assert.ok(sessions.length>=2);assert.equal(sessions[0].ip,undefined);assert.equal(sessions[0].user_agent,undefined);const current=sessions.find((s:any)=>s.current);await client.request(`/auth/sessions/${current.id}`,'PATCH',{name:'Private device name'});const stored=(await one('SELECT * FROM sessions WHERE id=$1',[current.id]))!;assert.equal(JSON.stringify(stored).includes('Private device name'),false);await client.request('/auth/sessions/others','DELETE');await device.request('/files','GET',undefined,401);});
 await check('Concurrent quota reservation admits one request and refunds aborts',async()=>{await admin.request(`/admin/users/${user.id}`,'PATCH',{quota:{concurrentUploads:1,storageBytes:1024**3}});const payload={name:'privacy-reservation.bin',size:1024**2,mime:'application/octet-stream',fingerprint:createHash('sha256').update(randomBytes(32)).digest('hex')};const results=await Promise.allSettled([client.request('/uploads','POST',payload),client.request('/uploads','POST',payload)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const upload=(results.find(r=>r.status==='fulfilled') as PromiseFulfilledResult<any>).value;uploads.push(upload.id);const balance=await client.request('/files/usage');assert.equal(balance.reserved_bytes,payload.size);assert.equal(balance.used_bytes,0);await client.request(`/uploads/${upload.id}/complete`,'POST',{},409);await client.request(`/uploads/${upload.id}/abort`,'POST',{});assert.equal((await client.request('/files/usage')).reserved_bytes,0);});
 let file:any,share:any,secret:string,visitor=new Client();
 await check('Completed upload transfers reservation to used storage',async()=>{const body=randomBytes(1024*128+17),checksum=createHash('sha256').update(body).digest('base64');const upload=await client.request('/uploads','POST',{name:'privacy-integrity.bin',size:body.length,mime:'application/octet-stream',fingerprint:createHash('sha256').update(body).digest('hex')});uploads.push(upload.id);const signed=await client.request(`/uploads/${upload.id}/sign`,'POST',{parts:[{number:1,checksum}]});const sent=await fetch(signed.parts[0].url,{method:'PUT',headers:signed.parts[0].headers,body});assert.equal(sent.status,200);file=await client.request(`/uploads/${upload.id}/complete`,'POST',{});secret=file.shareSecret;assert.equal(Buffer.from(secret,'base64url').length,32);const usage=await client.request('/files/usage');assert.equal(usage.reserved_bytes,0);assert.equal(usage.used_bytes,body.length);const grant=await client.request(`/files/${file.fileId}/download`,'POST',{});assert.deepEqual(Buffer.from(await(await fetch(grant.url)).arrayBuffer()),body);});
 await check('Share lookup stores only a keyed digest and a short-lived session',async()=>{share=await visitor.request('/shares/resolve','POST',{secret});const row=(await one('SELECT * FROM shares WHERE id=$1',[share.shareId]))!;assert.equal(JSON.stringify(row).includes(secret),false);assert.equal(row.slug,undefined);assert.match(row.capability_digest,/^[A-Za-z0-9_-]+:[a-f0-9]{64}$/);await visitor.request(`/public/shares/${share.shareId}`);await new Client().request(`/public/shares/${share.shareId}`,'GET',undefined,401);});
 await check('Owners and administrators cannot recover a share secret',async()=>{for(const route of ['/shares','/admin/shares','/admin/audit'])assert.equal(JSON.stringify(await admin.request(route)).includes(secret),false);assert.equal(JSON.stringify(await client.request('/shares')).includes(secret),false);});
 await check('Regeneration revokes old secret and old session',async()=>{const regenerated=await client.request(`/shares/${share.shareId}`,'PATCH',{regenerate:true});await new Client().request('/shares/resolve','POST',{secret},404);await visitor.request(`/public/shares/${share.shareId}`,'GET',undefined,401);secret=new URL(regenerated.url).hash.slice(1);const fresh=new Client();await fresh.request('/shares/resolve','POST',{secret});await fresh.request(`/public/shares/${share.shareId}`);});
 await check('A full share quota cannot prevent upload completion',async()=>{await admin.request(`/admin/users/${user.id}`,'PATCH',{quota:{shareCount:0}});await client.request('/shares','POST',{name:'Over limit',fileIds:[file.fileId]},403);const body=Buffer.from('quota completion check'),checksum=createHash('sha256').update(body).digest('base64');const u=await client.request('/uploads','POST',{name:'share-limit.txt',size:body.length,mime:'text/plain',fingerprint:createHash('sha256').update(body).digest('hex')});uploads.push(u.id);const signed=await client.request(`/uploads/${u.id}/sign`,'POST',{parts:[{number:1,checksum}]});assert.equal((await fetch(signed.parts[0].url,{method:'PUT',headers:signed.parts[0].headers,body})).status,200);const result=await client.request(`/uploads/${u.id}/complete`,'POST',{});assert.equal(result.shareSecret,undefined);assert.ok(result.fileId);});
 await check('IPv4 and IPv6 blocks persist across correlation rotation',async()=>{const address='2001:db8::8';await admin.request('/admin/blocks','POST',{ip:address,reason:'Privacy acceptance fixture'});const found=await one('SELECT ip FROM ip_blocks WHERE ip=ANY($1::text[])',[blockReferences(address)]);assert.ok(found);assert.equal(found.ip.includes(address),false);assert.notEqual(networkReference(address,'2026-09-06'),networkReference(address,'2026-09-07'));await admin.request('/admin/blocks','DELETE',{ip:found.ip});});
 await check('No plaintext identifiers or tokens in persisted operational records',async()=>{for(const table of ['sessions','uploads','downloads','audit_logs','security_events']){const rows=await query(`SELECT * FROM ${table} WHERE ${table==='sessions'?'user_id':table==='audit_logs'?'actor_id':table==='security_events'?'NULL::uuid':'owner_id'}=$1`,[user.id]);const serialized=JSON.stringify(rows);assert.equal(serialized.includes(email),false);assert.equal(serialized.includes(secret),false);for(const row of rows)if(row.ip)assert.match(row.ip,/^[A-Za-z0-9_-]+:\d{4}-\d{2}-\d{2}:[a-f0-9]{64}$/);}});
 await check('Private pages and API responses forbid indexing and caching',async()=>{for(const route of ['/s/','/admin/users','/account','/api/auth/me']){const response=await fetch(origin+route);assert.match(response.headers.get('x-robots-tag')??'',/noindex/);assert.equal(response.headers.get('referrer-policy'),'no-referrer');}});
 await check('Suspension invalidates active sessions without deleting account data',async()=>{await admin.request(`/admin/users/${user.id}`,'PATCH',{status:'SUSPENDED'});await client.request('/files','GET',undefined,401);const row=await one('SELECT account_id FROM users WHERE id=$1',[user.id]);assert.equal(row!.account_id,user.accountId);await admin.request(`/admin/users/${user.id}`,'PATCH',{status:'ACTIVE'});await client.request('/auth/login','POST',{email,password});assert.ok((await client.request('/files')).items.length>=2);});
 await report('privacy-acceptance',{at:new Date().toISOString(),checks,passed:checks.length});
}finally{await admin.request('/admin/settings','PUT',settings);await pool.end();}
