import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomBytes,createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {owner,Client,report,origin} from './helpers.js';
if(!process.env.TEST_ORIGIN||!origin.startsWith('https://')||!process.env.ASTRAFILE_TEST_SSH_HOST||!process.env.ASTRAFILE_TEST_SSH_KEY)throw Error('Explicit TEST_ORIGIN, ASTRAFILE_TEST_SSH_HOST and ASTRAFILE_TEST_SSH_KEY are required');
const admin=await owner(),bytes=randomBytes(4096),u=await admin.request('/uploads','POST',{name:'public-privacy-owned-check.bin',size:bytes.length,mime:'application/octet-stream',fingerprint:createHash('sha256').update(bytes).digest('hex')});
try{
 const sign=await admin.request(`/uploads/${u.id}/sign`,'POST',{parts:[{number:1,checksum:createHash('sha256').update(bytes).digest('base64')}]});assert.equal((await fetch(sign.parts[0].url,{method:'PUT',headers:sign.parts[0].headers,body:bytes})).status,200);const completed=await admin.request(`/uploads/${u.id}/complete`,'POST',{});const secret=completed.shareSecret;assert.equal(Buffer.from(secret,'base64url').length,32);
 const visitor=new Client(),share=await visitor.request('/shares/resolve','POST',{secret});await visitor.request(`/public/shares/${share.shareId}`);await new Client().request(`/public/shares/${share.shareId}`,'GET',undefined,401);
 for(const route of ['/shares','/admin/shares','/admin/audit'])assert.equal(JSON.stringify(await admin.request(route)).includes(secret),false);
 await admin.request(`/shares/${share.shareId}`,'PATCH',{regenerate:true});await new Client().request('/shares/resolve','POST',{secret},404);await visitor.request(`/public/shares/${share.shareId}`,'GET',undefined,401);
 const credentials=JSON.parse(await readFile(process.env.TEST_OWNER_FILE!,'utf8'));
 const python=`import sys,json,subprocess\np=json.load(sys.stdin)\ndef query(sql):\n return subprocess.check_output(['docker','exec','-i','astrafile-astrafile-postgres-1','psql','-U','astrafile','-d','astrafile','-Atc',sql],stderr=subprocess.DEVNULL,text=True).strip()\ndef quoted(v):return "'"+v.replace("'","''")+"'"\nraw_share=int(query("SELECT count(*) FROM shares s WHERE strpos(to_jsonb(s)::text,"+quoted(p['secret'])+")>0"))\nraw_email=int(query("SELECT count(*) FROM users u WHERE strpos(to_jsonb(u)::text,"+quoted(p['email'])+")>0"))\ncolumns=int(query("SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND ((table_name='users' AND column_name='email') OR (table_name='shares' AND column_name='slug'))"))\nnon_argon=int(query("SELECT count(*) FROM users WHERE password_hash IS NOT NULL AND password_hash NOT LIKE '$argon2id$%'"))\nlog_hits=0\nfor service in ['api','worker','proxy']:\n r=subprocess.run(['docker','logs','--since','2026-09-07T19:55:00Z','astrafile-astrafile-'+service+'-1'],stdout=subprocess.PIPE,stderr=subprocess.PIPE)\n log_hits+=(r.stdout+r.stderr).count(p['secret'].encode())\nprint(json.dumps({'rawShareDatabaseMatches':raw_share,'rawEmailDatabaseMatches':raw_email,'obsoletePlaintextColumns':columns,'nonArgon2Passwords':non_argon,'rawShareLogMatches':log_hits}))`;
 const shellQuote=(value:string)=>"'"+value.replaceAll("'","'\\''")+"'";
 const result=spawnSync('ssh',['-i',process.env.ASTRAFILE_TEST_SSH_KEY!,'-o','IdentitiesOnly=yes','-o','BatchMode=yes','-o','StrictHostKeyChecking=yes',process.env.ASTRAFILE_TEST_SSH_HOST!,'sudo -n python3 -c '+shellQuote(python)],{input:JSON.stringify({secret,email:credentials.email}),encoding:'utf8',windowsHide:true,timeout:30000});assert.equal(result.status,0,'Scoped database/log inspection failed');const evidence=JSON.parse(result.stdout);for(const value of Object.values(evidence))assert.equal(value,0);
 await report('public-privacy',{at:new Date().toISOString(),origin,...evidence,shareRegenerationRevokedSecretAndSession:true,anonymousIdAccessDenied:true,secretBytes:32});console.info('PASS public share capabilities, regeneration, Argon2id, email blind index, database and log checks');
}finally{await admin.request('/files/bulk','POST',{ids:[u.fileId],action:'delete'});await admin.request('/files/bulk','POST',{ids:[u.fileId],action:'purge',confirm:'DELETE PERMANENTLY'});}
