import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {owner,report,origin} from './helpers.js';
const manifest=JSON.parse(await readFile('output/verification/public-completed-source-manifest.json','utf8'));
const c=await owner(),grant=await c.request(`/files/${manifest.fileId}/download`,'POST',{}),full=createHash('sha256');let part=createHash('sha256'),partIndex=0,inPart=0,total=0;const started=performance.now();
const response=await fetch(grant.url);assert.equal(response.status,200);for await(const chunk of response.body!){full.update(chunk);let at=0;while(at<chunk.length){const count=Math.min(chunk.length-at,manifest.parts[partIndex].bytes-inPart);part.update(chunk.subarray(at,at+count));at+=count;inPart+=count;total+=count;if(inPart===manifest.parts[partIndex].bytes){assert.equal(part.digest('base64'),manifest.parts[partIndex].checksum,'Downloaded part differs from the original browser-signed checksum');part=createHash('sha256');partIndex++;inPart=0;if(partIndex%4===0)console.info(`Verified ${total/1024**2} MiB against original browser checksums`);}}}
const seconds=(performance.now()-started)/1000,sha256=full.digest('hex');assert.equal(total,manifest.bytes);assert.equal(partIndex,manifest.parts.length);assert.equal(sha256,manifest.fullSHA256);
const range=await fetch(grant.url,{headers:{range:'bytes=0-67108863'}});assert.equal(range.status,206);const ranged=createHash('sha256');let rangeBytes=0;for await(const chunk of range.body!){ranged.update(chunk);rangeBytes+=chunk.length;}assert.equal(rangeBytes,manifest.parts[0].bytes);assert.equal(ranged.digest('base64'),manifest.parts[0].checksum);
await report('public-postprivacy-download',{at:new Date().toISOString(),origin,bytes:total,source:'Existing completed 1 GiB random browser upload; each downloaded part matched its original client-signed SHA-256',browserUploadSecondsFromServerTimestamps:(Date.parse(manifest.completedAt)-Date.parse(manifest.createdAt))/1000,downloadSeconds:seconds,downloadMBps:total/seconds/1e6,sha256,allOriginalPartChecksumsMatch:true,fullWorkerChecksumMatches:true,range206:true,rangeOriginalChecksumMatches:true,certificateVerification:true});console.info('PASS existing public 1 GiB download, original part checksums, full SHA-256 and Range/206');
