import {createContext,useContext,useEffect,useRef,useState,type ReactNode,type FormEvent} from 'react';
import {File,FileText,Image,Film,Music,Archive,Folder,Check,X,Loader2,ChevronDown,ArrowUpRight,Copy} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api,bytes} from './api.js';
import {useApp} from './context.js';
import {useI18n,type Key} from './i18n.js';
export function Logo(){const{config}=useApp();return <Link to="/" className="logo" aria-label="AstraFile home"><span className="logo-mark">{config?.logoFileId?<img alt="" src={`/api/branding/logo?v=${config.logoFileId}`}/>:<svg viewBox="0 0 32 32" fill="none"><path d="m16 4 12 24H4L16 4Zm0 9-4 9h8l-4-9Z" fill="currentColor"/></svg>}</span>{config?.siteName??'AstraFile'}<span className="logo-dot">.</span></Link>;}
export function FileIcon({mime='',folder=false}:{mime?:string;folder?:boolean}){const Icon=folder?Folder:mime.startsWith('image')?Image:mime.startsWith('video')?Film:mime.startsWith('audio')?Music:/zip|rar|compressed/.test(mime)?Archive:/pdf|text/.test(mime)?FileText:File;const cls=folder?'folder':mime.startsWith('image')?'image':mime.startsWith('video')?'video':/zip|rar|compressed/.test(mime)?'archive':'file';return <span className={`file-icon ${cls}`}><Icon size={22} strokeWidth={1.5}/></span>;}
export function IconButton({label,children,onClick,disabled=false}:{label:string;children:ReactNode;onClick:()=>void;disabled?:boolean}){return <button type="button" className="icon-button" title={label} aria-label={label} onClick={onClick} disabled={disabled}>{children}</button>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export function Progress({value}:{value:number}){return <div className="progress" role="progressbar" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100}><span style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>;}
export function Empty({title,description,children}:{title:string;description?:string;children?:ReactNode}){return <div className="empty"><span className="empty-icon"><Folder size={32} strokeWidth={1}/></span><h3>{title}</h3>{description&&<p>{description}</p>}{children}</div>;}
export function Loading(){const{t}=useI18n();return <div className="loading" role="status"><Loader2 className="spin" size={20}/>{t('loading')}…</div>;}
export function ErrorBox({message}:{message:string}){return <div className="error-box" role="alert">{message}</div>;}
export function useData<T=any>(path:string|null,deps:unknown[]=[]){const[data,setData]=useState<T|null>(null),[loadedPath,setLoadedPath]=useState<string|null>(null),[error,setError]=useState(''),[errorCode,setErrorCode]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);useEffect(()=>{if(!path||!/^\/(files|folders|shares)([/?]|$)/.test(path))return;const changed=()=>setRevision(v=>v+1);window.addEventListener('astrafile:cloud-change',changed);return()=>window.removeEventListener('astrafile:cloud-change',changed);},[path]);useEffect(()=>{let active=true;if(!path){setLoading(false);return;}setLoading(true);api<T>(path).then(d=>{if(active){setLoadedPath(path);setData(d);setError('');setErrorCode('');}}).catch(e=>{if(active){setLoadedPath(path);setData(null);setError(e.message);setErrorCode(e.code??'UNKNOWN');}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path,revision,...deps]);return {data:loadedPath===path?data:null,error:loadedPath===path?error:'',errorCode:loadedPath===path?errorCode:'',loading:path!==null&&(loading||loadedPath!==path),reload:()=>setRevision(v=>v+1),setData};}
type Field={name:string;label:string;type?:string;value?:string|number;required?:boolean;options?:{value:string;label:string}[];hint?:string;min?:number;max?:number};
type DialogRequest={title:string;description?:string;fields?:Field[];confirm?:string;danger?:boolean;content?:ReactNode;onSubmit?:(data:Record<string,string>)=>Promise<void>};
const UI=createContext({toast:(_:string)=>{},dialog:(_:DialogRequest):Promise<Record<string,string>|null>=>Promise.resolve(null)});
export const useUI=()=>useContext(UI);
export function UIProvider({children}:{children:ReactNode}){
 const{t}=useI18n();const[toasts,setToasts]=useState<{id:number;message:string}[]>([]);const[request,setRequest]=useState<DialogRequest|null>(null);const resolver=useRef<(v:Record<string,string>|null)=>void>(()=>{});const dialogRef=useRef<HTMLDialogElement>(null);const[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const toast=(message:string)=>{const id=Date.now()+Math.random();setToasts(v=>[...v,{id,message}]);setTimeout(()=>setToasts(v=>v.filter(x=>x.id!==id)),4500);};
 const dialog=(req:DialogRequest)=>new Promise<Record<string,string>|null>(resolve=>{resolver.current=resolve;setRequest(req);setError('');});
 useEffect(()=>{if(request)dialogRef.current?.showModal();else dialogRef.current?.close();},[request]);
 const close=(v:Record<string,string>|null=null)=>{setRequest(null);resolver.current(v);};
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;try{await request?.onSubmit?.(values);close(values);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <UI.Provider value={{toast,dialog}}>{children}<div className="toasts" aria-live="polite">{toasts.map(x=><div className="toast" key={x.id}><Check size={16}/>{x.message}</div>)}</div><dialog ref={dialogRef} className="modal" onCancel={e=>{e.preventDefault();if(!busy)close();}} onClick={e=>{if(e.target===dialogRef.current&&!busy)close();}}>{request&&<form onSubmit={submit}><header><h2>{request.title}</h2><IconButton label={t('close')} disabled={busy} onClick={()=>close()}><X size={18}/></IconButton></header>{request.description&&<p className="muted">{request.description}</p>}{request.content}{request.fields?.map(f=><label className="field" key={f.name}><span>{f.label}</span>{f.options?<select aria-label={f.label} name={f.name} defaultValue={f.value} required={f.required}>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea aria-label={f.label} name={f.name} defaultValue={f.value} required={f.required}/>:<input aria-label={f.label} name={f.name} type={f.type??'text'} defaultValue={f.value} required={f.required} min={f.min} max={f.max} autoComplete={f.type==='password'?'new-password':'off'}/>}{f.hint&&<small>{f.hint}</small>}</label>)}{error&&<ErrorBox message={error}/>}<footer><button type="button" className="button secondary" disabled={busy} onClick={()=>close()}>{t('cancel')}</button><button type="submit" className={`button ${request.danger?'danger':''}`} disabled={busy}>{busy?<Loader2 className="spin" size={16}/>:request.confirm??t('save')}</button></footer></form>}</dialog></UI.Provider>;
}
export function Menu({children,label}:{children:ReactNode;label:string}){return <details className="menu"><summary aria-label={label}><span>•••</span></summary><div className="menu-panel" onClick={e=>(e.currentTarget.parentElement as HTMLDetailsElement).open=false}>{children}</div></details>;}
export function Stat({label,value,detail}:{label:string;value:ReactNode;detail?:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>;}
export function LinkResult({url}:{url:string}){const{t}=useI18n(),{toast}=useUI();return <div className="link-result"><input value={url} aria-label={t('link')} readOnly dir="ltr" onFocus={e=>e.target.select()}/><IconButton label={t('copyLink')} onClick={()=>{navigator.clipboard.writeText(url).then(()=>toast(t('copied'))).catch(()=>toast(url));}}><Copy size={18}/></IconButton><a className="icon-button" href={url} target="_blank" rel="noreferrer" aria-label={t('openShare')}><ArrowUpRight size={18}/></a></div>;}
export function JsonDetails({value}:{value:unknown}){return <pre className="json-details" dir="ltr">{JSON.stringify(value,null,2)}</pre>;}
