import {useEffect,useRef,useState,useSyncExternalStore,type DragEvent} from 'react';
import {Upload,ArrowUp,ArrowUpRight,Pause,Play,X,RotateCcw,Check,FolderUp,WifiOff,ShieldCheck,Zap,RefreshCw,Files} from 'lucide-react';
import {Link} from 'react-router-dom';
import {uploads,type Transfer} from './engine.js';
import {useI18n} from '../i18n.js';
import {useApp} from '../context.js';
import {useUI,IconButton,Progress,FileIcon,LinkResult,Badge} from '../components.js';
import {api,bytes,speed} from '../api.js';
export function useTransfers(){useSyncExternalStore(uploads.subscribe,uploads.getSnapshot);return uploads.transfers;}
export function TransferCard({transfer:t}:{transfer:Transfer}){const{t:tr}=useI18n(),{toast,dialog}=useUI();const reselect=useRef<HTMLInputElement>(null);const invoke=(fn:()=>Promise<unknown>)=>void fn().catch(e=>toast(e.message));const percent=t.size?t.bytes/t.size*100:0;return <article className={`transfer-card ${t.state}`}><div className="transfer-top"><FileIcon/><div className="transfer-title"><strong title={t.name}>{t.name}</strong><span>{bytes(t.size)} <span className="dot">·</span> {tr(t.state)}</span></div><div className="transfer-actions">{t.state==='uploading'&&<IconButton label={tr('pause')} onClick={()=>invoke(()=>uploads.pause(t.id))}><Pause size={17}/></IconButton>}{['paused','failed'].includes(t.state)&&<IconButton label={tr('reselect')} onClick={()=>reselect.current?.click()}><Play size={17}/></IconButton>}{t.state!=='complete'&&t.state!=='finalizing'&&<IconButton label={tr('cancel')} onClick={()=>void dialog({title:tr('cancel'),description:tr('cancelTransfer'),confirm:tr('confirm'),danger:true,onSubmit:async()=>{await uploads.cancel(t.id);}})}><X size={17}/></IconButton>}{t.state==='complete'&&<span className="complete-check"><Check size={19}/></span>}</div></div><input type="file" hidden ref={reselect} onChange={e=>{const f=e.target.files?.[0];if(f)invoke(()=>uploads.resume(t.id,f));e.target.value='';}}/>{t.state==='complete'?<div className="transfer-result"><span>{tr(t.shareSecret?'transferComplete':'complete')}</span>{t.shareSecret?<LinkResult url={`${location.origin}/s/#${t.shareSecret}`}/>:<Link className="button secondary" to="/drive">{tr('files')}</Link>}</div>:<><Progress value={percent}/><div className="transfer-metrics"><span>{bytes(t.bytes)} / {bytes(t.size)}</span><strong>{percent.toFixed(1)}%</strong></div>{t.state==='uploading'&&<div className="transfer-metrics"><span>{speed(t.rate)} <span className="dot">·</span> {t.active} {tr('activeParts')}</span><span>{t.rate>0?`${Math.ceil((t.size-t.bytes)/t.rate/60)} min ${tr('remaining')}`:'—'}</span></div>}{t.average>0&&t.state==='uploading'&&<small>{tr('average')}: {speed(t.average)} · {tr('remainingBytes')}: {bytes(t.size-t.bytes)}</small>}{t.error&&<p className="transfer-error">{t.error} {t.retries>0&&`(${tr('retry')}: ${t.retries})`}</p>}{t.state==='paused'&&<small>{tr('resumableHint')}</small>}</>}</article>;}
async function droppedFiles(items:DataTransferItemList):Promise<{file:File;path:string}[]>{
 const results:{file:File;path:string}[]=[];
 async function walk(entry:any,parent=''){if(entry.isFile){const file:File=await new Promise((resolve,reject)=>entry.file(resolve,reject));results.push({file,path:parent});}else if(entry.isDirectory){const reader=entry.createReader();while(true){const entries:any[]=await new Promise((resolve,reject)=>reader.readEntries(resolve,reject));if(!entries.length)break;for(const e of entries)await walk(e,`${parent}${entry.name}/`);}}}
 for(const item of Array.from(items)){const entry=item.webkitGetAsEntry?.();if(entry)await walk(entry);else{const f=item.getAsFile();if(f)results.push({file:f,path:''});}}
 return results;
}
export function Uploader({folderId,compact=false}:{folderId?:string;compact?:boolean}){
 const{t}=useI18n(),{config,refresh}=useApp(),{toast}=useUI();const[drag,setDrag]=useState(false),[preparing,setPreparing]=useState(false);const input=useRef<HTMLInputElement>(null),folder=useRef<HTMLInputElement>(null);const transfers=useTransfers();
 async function addFiles(selected:{file:File;path:string}[]){setPreparing(true);try{await api('/auth/guest','POST',{});const folders=new Map<string,string>();if(folderId)folders.set('',folderId);for(const {file,path:relative}of selected){let parent=folderId;let key='';for(const name of relative.split('/').filter(Boolean)){key+=name+'/';if(!folders.has(key)){const created=await api('/folders','POST',{name,parentId:parent??null});folders.set(key,created.id);}parent=folders.get(key);}await uploads.add(file,parent);}await refresh();}catch(e){toast((e as Error).message);}finally{setPreparing(false);}}
 useEffect(()=>{const pasted=(e:ClipboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;const files=Array.from(e.clipboardData?.files??[]);if(files.length){e.preventDefault();void addFiles(files.map(file=>({file,path:''})));}};document.addEventListener('paste',pasted);return()=>document.removeEventListener('paste',pasted);},[folderId]);
 async function drop(e:DragEvent){e.preventDefault();setDrag(false);const files=await droppedFiles(e.dataTransfer.items);void addFiles(files);}
 return <><div className={`dropzone ${drag?'dragging':''} ${compact?'compact':''}`} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>void drop(e)}><div className="upload-symbol"><ArrowUp size={30} strokeWidth={1.5}/></div><h2>{preparing?t('preparing'):t('dropFiles')}</h2><p>{t('dropHint')}</p><div className="drop-actions"><button className="button" disabled={preparing||config?.readOnly||config?.maintenance} onClick={()=>input.current?.click()}><Upload size={17}/>{t('selectFiles')}</button><button className="button secondary" disabled={preparing} onClick={()=>folder.current?.click()}><FolderUp size={17}/>{t('uploadFolder')}</button></div><span className="drop-limit">{config?.maxFileBytes?`${bytes(config.maxFileBytes)} / ${t('files')}`:''} <span className="dot">·</span> {t('resumable')}</span><input ref={input} hidden type="file" multiple aria-label={t('selectFiles')} onChange={e=>{void addFiles(Array.from(e.target.files??[]).map(file=>({file,path:''})));e.target.value='';}}/><input ref={folder} hidden type="file" multiple {...{webkitdirectory:''} as any} aria-label={t('uploadFolder')} onChange={e=>{void addFiles(Array.from(e.target.files??[]).map(file=>({file,path:file.webkitRelativePath.split('/').slice(0,-1).join('/')})));e.target.value='';}}/></div>{transfers.length>0&&<section className="transfers"><div className="section-heading"><h2>{t('transfer')}</h2><Badge>{transfers.filter(t=>t.state==='complete').length} / {transfers.length}</Badge></div>{transfers.map(t=><TransferCard transfer={t} key={t.id}/>)}</section>}</>;
}
export function UploadPage({heading,description}:{heading?:string;description?:string}={}){const{t}=useI18n(),{user,config}=useApp();return <div className="upload-page"><div className="intro"><span className="eyebrow">ASTRAFILE / {t('newUpload')}</span><h1>{config?.homepageTitle||heading||t('dropTitle')}</h1><p>{config?.homepageSubtitle||description||t('dropSub')}</p></div><Uploader/><div className="feature-row">{[[Zap,'direct','directDetail'],[RefreshCw,'resumable','resumableDetail'],[ShieldCheck,'original','originalDetail']].map(([Icon,title,detail]:any)=><div className="feature" key={title}><Icon size={20} strokeWidth={1.5}/><h3>{t(title)}</h3><p>{t(detail)}</p></div>)}</div><p className="privacy-note"><ShieldCheck size={14}/>{t('privacy')}</p>{(!user||user.anonymous)&&<p className="guest-note">{t('guestNote')} <Link to="/register">{t('signUp')} <ArrowUpRight size={13}/></Link></p>}</div>;}
