import {accountOverrideSchema,entitlements} from './entitlements.js';
import {blockReference,redact} from '../../../packages/privacy/index.js';
import os from 'node:os';
import {transferSnapshot} from './transfer-metrics.js';
import {brandingFile} from './branding.js';
import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {env,settingsSchema} from '../../../packages/config/index.js';
import {query,one,tx,audit,settings} from '../../../packages/database/index.js';
import {storage} from '../../../packages/storage/index.js';
import {admin,moderator,support} from './auth.js';
import {paramId} from './files.js';
import {disk,redis,requireValue,ApiError,enqueue} from './lib.js';
import {roleSchema} from '../../../packages/validation/index.js';
let cpuSample={at:performance.now(),usage:process.cpuUsage(),percent:null as number|null};
function cpuPercent(){const at=performance.now();if(at-cpuSample.at>1000){const usage=process.cpuUsage(),delta=(usage.user-cpuSample.usage.user)+(usage.system-cpuSample.usage.system);cpuSample={at,usage,percent:delta/(at-cpuSample.at)/10};}return cpuSample.percent;}
export async function health(){
 const checks=await Promise.allSettled([one('SELECT 1'),redis.ping(),storage.health(),redis.get('astrafile:worker:heartbeat')]);
 const services=checks.map((r,i)=>({name:['database','redis','storage','worker'][i],healthy:r.status==='fulfilled'&&(i!==3||!!r.value&&Date.now()-Number(r.value)<120000)}));
 return {healthy:services.every(s=>s.healthy),services,uptime:process.uptime()};
}
export async function overview(){
 const [totals,uploads,downloads,users,space,jobs,series,h]=await Promise.all([
  one("SELECT count(*) FILTER(WHERE f.state='AVAILABLE')::int files,COALESCE(sum(o.size) FILTER(WHERE f.state='AVAILABLE'),0)::bigint bytes FROM files f JOIN file_objects o ON o.id=f.object_id"),
  one("SELECT count(*) FILTER(WHERE state IN ('CREATED','UPLOADING','FINALIZING'))::int active,count(*) FILTER(WHERE state='FAILED')::int failed,count(*) FILTER(WHERE created_at>=date_trunc('day',now()))::int today,COALESCE(sum(size) FILTER(WHERE state='AVAILABLE' AND updated_at>=date_trunc('day',now())),0)::bigint completed_today FROM uploads"),
  one("SELECT count(*) FILTER(WHERE created_at>=date_trunc('day',now()))::int today,COALESCE(sum(bytes_authorized) FILTER(WHERE created_at>=date_trunc('day',now())),0)::bigint bytes_today,COALESCE(sum(bytes_authorized) FILTER(WHERE created_at>=date_trunc('month',now())),0)::bigint bytes_month FROM downloads"),
  one('SELECT count(*) FILTER(WHERE NOT anonymous)::int registered,count(*) FILTER(WHERE anonymous)::int guests FROM users'),disk(),
  one("SELECT count(*) FILTER(WHERE status='PENDING')::int pending,count(*) FILTER(WHERE status='FAILED')::int failed FROM background_jobs"),
  query("SELECT d::date date,COALESCE((SELECT sum(size) FROM uploads WHERE state='AVAILABLE' AND updated_at>=d AND updated_at<d+interval '1 day'),0)::bigint uploaded,COALESCE((SELECT sum(bytes_authorized) FROM downloads WHERE created_at>=d AND created_at<d+interval '1 day'),0)::bigint download_authorized FROM generate_series(date_trunc('day',now())-interval '13 days',date_trunc('day',now()),interval '1 day') d"),health()
 ]);
 return {totals,uploads,downloads,users,space,jobs,series,health:h,system:{cpuCount:os.cpus().length,loadAverage:os.loadavg(),totalMemory:os.totalmem(),freeMemory:os.freemem(),apiMemory:process.memoryUsage().rss,apiCpuPercent:cpuPercent(),uptime:process.uptime()},traffic:transferSnapshot(),transferAccounting:'Download quotas count signed authorizations. Storage traffic counters include background integrity reads and update at request completion.'};
}
export async function adminRoutes(app:FastifyInstance){
 app.get('/api/admin/overview',async req=>{support(req);return overview();});
 app.get('/api/admin/health',async req=>{support(req);return health();});
 app.get('/api/admin/events',async(req,reply)=>{
  support(req);reply.hijack();reply.raw.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','X-Accel-Buffering':'no'});
  let busy=false;const tick=async()=>{if(busy)return;busy=true;try{const current=await one("SELECT u.status,u.role FROM users u JOIN sessions s ON s.user_id=u.id WHERE u.id=$1 AND s.id=$2 AND s.expires_at>now()",[req.user!.id,req.sessionId]);if(!current||current.status!=='ACTIVE'||!['OWNER','ADMIN','MODERATOR','SUPPORT'].includes(current.role)){reply.raw.end();return;}reply.raw.write(`event: health\ndata: ${JSON.stringify(await health())}\n\n`);}catch{reply.raw.write('event: health\ndata: {"healthy":false}\n\n');}finally{busy=false;}};
  const timer=setInterval(tick,15000);req.raw.on('close',()=>clearInterval(timer));reply.raw.on('close',()=>clearInterval(timer));await tick();
 });
 app.get('/api/admin/:module',async req=>{
  support(req);const {module}=z.object({module:z.enum(['files','uploads','shares','users','storage','security','jobs','audit','analytics','settings','api','reports','notifications'])}).parse(req.params);
  const p=z.object({q:z.string().max(150).default(''),offset:z.coerce.number().int().min(0).max(1000000).default(0),state:z.string().max(30).default('')}).parse(req.query);const search=`%${p.q.replace(/[%_\\]/g,'\\$&')}%`;
  if(['settings','api'].includes(module))admin(req);
  if(module==='settings')return {settings:await settings(),smtpConfigured:!!env.SMTP_URL,scannerConfigured:!!env.SCAN_COMMAND};
  if(module==='storage'){const start=performance.now();await storage.health();return {backend:{type:'S3 compatible',endpoint:new URL(env.S3_ENDPOINT).origin,bucket:env.S3_BUCKET,healthy:true,latencyMs:performance.now()-start},disk:await disk(),objects:await one("SELECT count(*)::int count,COALESCE(sum(size),0)::bigint bytes FROM file_objects WHERE state NOT IN ('PURGED','PROCESSING')"),multipart:await one("SELECT count(*)::int count,COALESCE(sum(bytes_confirmed),0)::bigint bytes FROM uploads WHERE state IN ('UPLOADING','FINALIZING','FAILED')"),reconciliation:await one("SELECT detail,updated_at,status FROM background_jobs WHERE kind='reconcile' ORDER BY updated_at DESC LIMIT 1"),history:await query('SELECT * FROM storage_usage ORDER BY created_at DESC LIMIT 100')};}
  if(module==='analytics')return {series:(await overview()).series,downloads:await query("SELECT date_trunc('day',created_at) AS date,count(*)::int grants,sum(bytes_authorized)::bigint bytes FROM downloads GROUP BY 1 ORDER BY 1 DESC LIMIT 30"),note:'Bandwidth is reserved per signed download authorization; a direct URL can be reused until expiry.'};
  if(module==='security')return {items:await query('SELECT * FROM security_events ORDER BY created_at DESC LIMIT 100 OFFSET $1',[p.offset]),blocks:await query('SELECT * FROM ip_blocks ORDER BY created_at DESC'),reports:await query("SELECT r.*,s.id share_id FROM abuse_reports r LEFT JOIN shares s ON s.id=r.share_id WHERE r.status='OPEN' ORDER BY r.created_at DESC LIMIT 100")};
  const statements:Record<string,string>={
   files:`SELECT f.*,u.account_id owner,o.object_key,o.expected_size size,o.detected_mime,o.sha256,o.checksum_sha256,o.etag,(SELECT ip FROM uploads WHERE file_id=f.id ORDER BY created_at LIMIT 1) upload_ip,(SELECT json_agg(json_build_object('id',s.id,'enabled',s.enabled)) FROM share_items i JOIN shares s ON s.id=i.share_id WHERE i.file_id=f.id) shares FROM files f JOIN users u ON u.id=f.owner_id JOIN file_objects o ON o.id=f.object_id WHERE (f.name ILIKE $1 OR f.id::text ILIKE $1 OR u.account_id ILIKE $1 OR o.object_key ILIKE $1 OR o.sha256 ILIKE $1 OR EXISTS(SELECT 1 FROM share_items i JOIN shares s ON s.id=i.share_id WHERE i.file_id=f.id AND s.id::text ILIKE $1)) AND ($3='' OR f.state::text=$3) ORDER BY f.created_at DESC LIMIT 100 OFFSET $2`,
   uploads:"SELECT u.*,f.name,usr.account_id owner,(SELECT count(*)::int FROM upload_parts p WHERE p.upload_id=u.id AND p.etag IS NOT NULL) confirmed_parts FROM uploads u JOIN files f ON f.id=u.file_id JOIN users usr ON usr.id=u.owner_id WHERE (f.name ILIKE $1 OR usr.account_id ILIKE $1 OR u.id::text ILIKE $1) AND ($3='' OR u.state::text=$3) ORDER BY u.created_at DESC LIMIT 100 OFFSET $2",
   shares:"SELECT s.id,s.name,s.owner_id,u.account_id owner,s.enabled,s.visibility,s.expires_at,s.download_count,s.view_count,s.max_downloads,s.password_hash IS NOT NULL protected,s.created_at FROM shares s JOIN users u ON u.id=s.owner_id WHERE (s.name ILIKE $1 OR s.id::text ILIKE $1 OR u.account_id ILIKE $1) AND ($3='' OR s.visibility=$3) ORDER BY s.created_at DESC LIMIT 100 OFFSET $2",
   users:"SELECT u.id,u.name,u.account_id,u.plan_id,u.email_status,u.email_verified_at,u.role,u.status,u.anonymous,u.quota,u.created_at,(SELECT COALESCE(sum(o.expected_size),0)::bigint FROM files f JOIN file_objects o ON o.id=f.object_id WHERE f.owner_id=u.id AND f.state NOT IN ('PURGED','EXPIRED')) storage_bytes,(SELECT COALESCE(sum(bytes_authorized),0)::bigint FROM downloads WHERE owner_id=u.id) bandwidth_authorized FROM users u WHERE (u.name ILIKE $1 OR u.account_id ILIKE $1 OR u.id::text ILIKE $1) AND ($3='' OR u.status=$3) ORDER BY u.created_at DESC LIMIT 100 OFFSET $2",
   jobs:"SELECT * FROM background_jobs WHERE (kind ILIKE $1 OR target ILIKE $1) AND ($3='' OR status=$3) ORDER BY updated_at DESC LIMIT 100 OFFSET $2",
   audit:"SELECT a.*,u.name actor FROM audit_logs a LEFT JOIN users u ON u.id=a.actor_id WHERE (a.action ILIKE $1 OR a.target ILIKE $1 OR u.account_id ILIKE $1) AND ($3='' OR a.action=$3) ORDER BY a.created_at DESC LIMIT 100 OFFSET $2",
   api:"SELECT k.id,k.owner_id,k.name,k.prefix,k.scopes,k.expires_at,k.revoked_at,k.last_used_at,k.created_at,u.account_id owner FROM api_keys k JOIN users u ON u.id=k.owner_id WHERE (k.name ILIKE $1 OR u.account_id ILIKE $1) AND ($3='' OR k.name=$3) ORDER BY k.created_at DESC LIMIT 100 OFFSET $2",
   reports:"SELECT r.*,s.id share_id FROM abuse_reports r LEFT JOIN shares s ON s.id=r.share_id WHERE r.reason ILIKE $1 AND ($3='' OR r.status=$3) ORDER BY r.created_at DESC LIMIT 100 OFFSET $2",
   notifications:"SELECT * FROM notifications WHERE message ILIKE $1 AND ($3='' OR kind=$3) ORDER BY created_at DESC LIMIT 100 OFFSET $2"
  };
  const items=await query(statements[module],[search,p.offset,p.state]);if(module==='users')return {items:await Promise.all(items.map(async u=>({...u,...await entitlements(u.id),...await one('SELECT used_bytes,reserved_bytes FROM account_storage_usage WHERE owner_id=$1',[u.id])})))};return {items};
 });
 app.patch('/api/admin/users/:id',async req=>{
  const actor=admin(req),id=paramId(req);const i=z.object({role:roleSchema.optional(),status:z.enum(['PENDING','ACTIVE','SUSPENDED','DISABLED']).optional(),quota:accountOverrideSchema.nullable().optional(),planId:z.string().regex(/^[A-Z][A-Z0-9_-]{1,30}$/).optional(),resetSessions:z.boolean().optional()}).parse(req.body);
  if(i.role&&actor.role!=='OWNER')throw new ApiError(403,'Only an owner may change roles.');
  await tx(async db=>{await db.query('SELECT pg_advisory_xact_lock(74392103)');const u=requireValue(await one('SELECT * FROM users WHERE id=$1 FOR UPDATE',[id],db));if(u.role==='OWNER'&&actor.role!=='OWNER')throw new ApiError(403,'An administrator cannot change an owner account.');if(u.role==='OWNER'&&((i.role&&i.role!=='OWNER')||(i.status&&i.status!=='ACTIVE'))){const owners=await one("SELECT count(*)::int n FROM users WHERE role='OWNER' AND status='ACTIVE'",[],db);if(owners!.n<=1)throw new ApiError(409,'The final active owner cannot be removed or suspended.');}if(u.anonymous&&i.role&&i.role!=='USER')throw new ApiError(400,'Anonymous users cannot receive privileged roles.');await query('UPDATE users SET role=COALESCE($2::user_role,role),status=COALESCE($3,status),quota=CASE WHEN $4 THEN $5::jsonb ELSE quota END WHERE id=$1',[id,i.role??null,i.status??null,i.quota!==undefined,i.quota?JSON.stringify(i.quota):null],db);if(i.planId){requireValue(await one('SELECT id FROM plans WHERE id=$1 AND enabled',[i.planId],db));await query("UPDATE users SET plan_id=$2,subscription_state='MANUAL' WHERE id=$1",[id,i.planId],db);}if(i.quota!==undefined){await query('DELETE FROM quotas WHERE user_id=$1',[id],db);if(i.quota)await query('INSERT INTO quotas(user_id,policy) VALUES($1,$2)',[id,JSON.stringify(i.quota)],db);}if(i.resetSessions||i.status==='SUSPENDED'||i.status==='DISABLED'||i.role)await query('DELETE FROM sessions WHERE user_id=$1',[id],db);await audit(actor.id,'admin.user.updated',u.account_id,{before:{role:u.role,status:u.status,quota:u.quota},after:i},req.ip,db);});return {ok:true};
 });
 app.put('/api/admin/settings',async req=>{const actor=admin(req);const next=settingsSchema.parse(req.body);for(const id of [next.logoFileId,next.faviconFileId])if(id)await brandingFile(id);if(next.scanningEnabled&&!env.SCAN_COMMAND)throw new ApiError(400,'Configure a local scanner command before enabling scanning.');if(next.warningFreeGiB<next.minimumFreeGiB)throw new ApiError(400,'Warning threshold must be at least the stop-upload threshold.');await tx(async db=>{const before=await settings(db);await query('UPDATE settings SET value=$1,updated_at=now() WHERE id=1',[JSON.stringify(next)],db);await audit(actor.id,'settings.changed','global',{before,after:next},req.ip,db);});return {ok:true};});
 app.post('/api/admin/jobs',async req=>{const actor=admin(req);const i=z.object({kind:z.enum(['cleanup','reconcile','statistics','backup'])}).parse(req.body);await enqueue(i.kind,'manual');await audit(actor.id,'job.requested',i.kind,{},req.ip);return {ok:true};});
 app.post('/api/admin/jobs/:id/retry',async req=>{const actor=admin(req),id=paramId(req);requireValue(await one("UPDATE background_jobs SET status='PENDING',attempts=0,error=NULL,updated_at=now() WHERE id=$1 AND status='FAILED' RETURNING id",[id]));await audit(actor.id,'job.retried',id,{},req.ip);return {ok:true};});
 app.post('/api/admin/blocks',async req=>{const actor=moderator(req);const i=z.object({ip:z.union([z.ipv4(),z.ipv6()]),reason:z.string().min(3).max(500),expiresAt:z.iso.datetime().nullable().default(null)}).parse(req.body);await query('INSERT INTO ip_blocks(ip,reason,actor_id,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT(ip) DO UPDATE SET reason=$2,expires_at=$4',[blockReference(i.ip),redact(i.reason),actor.id,i.expiresAt]);await audit(actor.id,'ip.blocked',blockReference(i.ip),{reason:i.reason},req.ip);return {ok:true};});
 app.delete('/api/admin/blocks',async req=>{const actor=moderator(req);const {ip}=z.object({ip:z.string().regex(/^[A-Za-z0-9_-]+:[a-f0-9]{64}$/)}).parse(req.body);await query('DELETE FROM ip_blocks WHERE ip=$1',[ip]);await audit(actor.id,'ip.unblocked',ip,{},req.ip);return {ok:true};});
 app.patch('/api/admin/reports/:id',async req=>{const actor=moderator(req),id=paramId(req);const i=z.object({status:z.enum(['RESOLVED','REJECTED']),decision:z.string().min(3).max(2000),disableShare:z.boolean().default(false)}).parse(req.body);await tx(async db=>{const r=requireValue(await one('UPDATE abuse_reports SET status=$2,decision=$3,actor_id=$4 WHERE id=$1 RETURNING share_id',[id,i.status,i.decision,actor.id],db));if(i.disableShare)await query('UPDATE shares SET enabled=false,version=version+1 WHERE id=$1',[r.share_id],db);await audit(actor.id,'abuse.reviewed',id,i,req.ip,db);});return {ok:true};});
 app.delete('/api/admin/keys/:id',async req=>{const actor=admin(req),id=paramId(req);await query('UPDATE api_keys SET revoked_at=now() WHERE id=$1',[id]);await audit(actor.id,'admin.api-key.revoked',id,{},req.ip);return {ok:true};});
}
