import type {FastifyInstance} from 'fastify';
import {z} from 'zod';
import {readFile} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import path from 'node:path';
import {one,query,tx,audit} from '../../../packages/database/index.js';
import {pageContent,seoSchema,escapeHtml,type PageContent} from '../../../packages/content/index.js';
import {env} from '../../../packages/config/index.js';
import {admin} from './auth.js';
import {paramId} from './files.js';
import {ApiError,requireValue} from './lib.js';
export async function seoSettings(){return seoSchema.parse((await one('SELECT value FROM seo_settings WHERE id=1'))?.value??{});}
const pagePath=(lang:string,slug:string)=>`/${lang}${slug==='home'?'':'/'+slug}`;
export async function publicPage(slug:string,lang:'ar'|'en'){
 const row=requireValue(await one('SELECT id,slug,kind,published,updated_at FROM cms_pages WHERE slug=$1 AND published IS NOT NULL',[slug]));
 const content=pageContent.parse(row.published),seo=await seoSettings(),local=content[lang],base=(seo.canonicalBase||env.APP_ORIGIN).replace(/\/$/,''),canonical=local.canonical||base+pagePath(lang,slug);
 return {id:row.id,slug,kind:row.kind,updatedAt:row.updated_at,title:local.title,html:local.html,supportEmail:content.supportEmail,supportLinks:content.supportLinks,meta:{title:local.seoTitle||(slug==='home'?seo[lang].title:`${local.title}${seo.separator}${seo.siteName}`),description:local.description||seo[lang].description,keywords:local.keywords||seo[lang].keywords,canonical,indexable:seo.indexable&&content.indexable,ogTitle:local.ogTitle||local.seoTitle||local.title,ogDescription:local.ogDescription||local.description||seo[lang].description,image:local.image||seo.image||base+'/social-card.svg',twitterTitle:local.twitterTitle||local.ogTitle||local.title,twitterDescription:local.twitterDescription||local.description||seo[lang].description,twitterImage:local.twitterImage||local.image||seo.image||base+'/social-card.svg',locale:lang==='ar'?'ar_AR':'en_US',alternateLocale:lang==='ar'?'en_US':'ar_AR',alternates:{en:content.en.canonical||base+pagePath('en',slug),ar:content.ar.canonical||base+pagePath('ar',slug),'x-default':base+pagePath('en',slug)},googleVerification:seo.googleVerification,logo:seo.logo,favicon:seo.favicon||base+'/favicon.svg',tracking:seo.trackingEnabled?{analyticsId:seo.analyticsId,tagManagerId:seo.tagManagerId}:null,structuredData:{'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':base+'/#website',name:seo.siteName,url:base},{'@type':row.kind==='contact'?'ContactPage':row.kind==='about'?'AboutPage':'WebPage',name:local.title,url:canonical,inLanguage:lang,isPartOf:{'@id':base+'/#website'}},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:seo[lang].title,item:base+pagePath(lang,'home')},...(slug==='home'?[]:[{'@type':'ListItem',position:2,name:local.title,item:canonical}])]}]}}};
}
function head(page:Awaited<ReturnType<typeof publicPage>>){const m=page.meta;const meta=(name:string,value:string,property=false)=>`<meta data-astra-seo ${property?'property':'name'}="${name}" content="${escapeHtml(value)}">`;return `<title>${escapeHtml(m.title)}</title>`+meta('description',m.description)+meta('keywords',m.keywords)+meta('robots',m.indexable?'index,follow':'noindex,nofollow')+`<link data-astra-seo rel="canonical" href="${escapeHtml(m.canonical)}">`+Object.entries(m.alternates).map(([language,url])=>`<link data-astra-seo rel="alternate" hreflang="${language}" href="${escapeHtml(url)}">`).join('')+meta('og:type','website',true)+meta('og:title',m.ogTitle,true)+meta('og:description',m.ogDescription,true)+meta('og:url',m.canonical,true)+meta('og:locale',m.locale,true)+meta('og:locale:alternate',m.alternateLocale,true)+(m.image?meta('og:image',m.image,true):'')+meta('twitter:card',m.twitterImage?'summary_large_image':'summary')+meta('twitter:title',m.twitterTitle)+meta('twitter:description',m.twitterDescription)+(m.twitterImage?meta('twitter:image',m.twitterImage):'')+(m.googleVerification?meta('google-site-verification',m.googleVerification):'')+`<link data-astra-seo rel="icon" href="${escapeHtml(m.favicon)}">`+`<script data-astra-seo type="application/ld+json">${JSON.stringify(m.structuredData).replace(/</g,'\\u003c')}</script>`;}
export async function contentRoutes(app:FastifyInstance){
 app.get('/api/pages',async()=>({items:(await query('SELECT slug,kind,published,updated_at FROM cms_pages WHERE published IS NOT NULL ORDER BY kind,slug')).map(row=>({slug:row.slug,kind:row.kind,en:row.published.en.title,ar:row.published.ar.title,updatedAt:row.updated_at}))}));
 app.get('/api/pages/:slug',async req=>{const {slug}=z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{0,70}$/)}).parse(req.params),{lang}=z.object({lang:z.enum(['ar','en']).default('en')}).parse(req.query);return publicPage(slug,lang);});
 app.get('/api/admin/pages',async req=>{admin(req);return {items:await query('SELECT id,slug,kind,revision,updated_at,published IS NOT NULL published,draft FROM cms_pages ORDER BY kind,slug')};});
 app.get('/api/admin/pages/:id',async req=>{admin(req);return {page:requireValue(await one('SELECT * FROM cms_pages WHERE id=$1',[paramId(req)])),revisions:await query('SELECT id,revision,created_at FROM cms_revisions WHERE page_id=$1 ORDER BY revision DESC',[paramId(req)])};});
 const edit=z.object({slug:z.string().regex(/^[a-z0-9][a-z0-9-]{0,70}$/).refine(s=>!['api','admin','support','account','drive','shares','s','login','register'].includes(s)),kind:z.enum(['page','home','about','contact','terms','privacy','acceptable-use','abuse','copyright']).default('page'),content:pageContent,publish:z.boolean().optional(),expectedRevision:z.number().int().positive().optional()});
 app.post('/api/admin/pages',async req=>{const actor=admin(req),input=edit.parse(req.body);return tx(async db=>{const row=requireValue(await one('INSERT INTO cms_pages(slug,kind,draft,published,published_at) VALUES($1,$2,$3,$4,CASE WHEN $4::jsonb IS NOT NULL THEN now() ELSE NULL END) RETURNING id',[input.slug,input.kind,JSON.stringify(input.content),input.publish?JSON.stringify(input.content):null],db));await query('INSERT INTO cms_revisions(page_id,revision,snapshot,actor_id) VALUES($1,1,$2,$3)',[row.id,JSON.stringify(input.content),actor.id],db);await audit(actor.id,'cms.created',row.id,{published:!!input.publish},req.ip,db);return row;});});
 app.put('/api/admin/pages/:id',async req=>{const actor=admin(req),id=paramId(req),input=edit.parse(req.body);return tx(async db=>{const row=requireValue(await one('SELECT revision FROM cms_pages WHERE id=$1 FOR UPDATE',[id],db));if(input.expectedRevision!==row.revision)throw new ApiError(409,'This page changed. Reload before saving.','VERSION_CONFLICT');await query('UPDATE cms_pages SET slug=$2,kind=$3,draft=$4,published=CASE WHEN $5 THEN CASE WHEN $6 THEN $4::jsonb ELSE NULL END ELSE published END,published_at=CASE WHEN $6 THEN now() ELSE published_at END,revision=revision+1,updated_at=now() WHERE id=$1',[id,input.slug,input.kind,JSON.stringify(input.content),input.publish!==undefined,input.publish??false],db);await query('INSERT INTO cms_revisions(page_id,revision,snapshot,actor_id) VALUES($1,$2,$3,$4)',[id,row.revision+1,JSON.stringify(input.content),actor.id],db);await audit(actor.id,'cms.updated',id,{published:input.publish},req.ip,db);return {ok:true};});});
 app.post('/api/admin/pages/:id/restore',async req=>{const actor=admin(req),id=paramId(req),input=z.object({revisionId:z.uuid(),expectedRevision:z.number().int().positive()}).parse(req.body);return tx(async db=>{const current=requireValue(await one('SELECT revision FROM cms_pages WHERE id=$1 FOR UPDATE',[id],db));if(current.revision!==input.expectedRevision)throw new ApiError(409,'This page changed. Reload before restoring.','VERSION_CONFLICT');const prior=requireValue(await one('SELECT snapshot FROM cms_revisions WHERE id=$1 AND page_id=$2',[input.revisionId,id],db)),safe=pageContent.parse(prior.snapshot);await query('UPDATE cms_pages SET draft=$2,revision=revision+1,updated_at=now() WHERE id=$1',[id,JSON.stringify(safe)],db);await query('INSERT INTO cms_revisions(page_id,revision,snapshot,actor_id) VALUES($1,$2,$3,$4)',[id,current.revision+1,JSON.stringify(safe),actor.id],db);await audit(actor.id,'cms.restored',id,{},req.ip,db);return {ok:true};});});
 app.get('/api/admin/seo',async req=>{admin(req);const seo=await seoSettings(),pages=await query('SELECT slug,published FROM cms_pages WHERE published IS NOT NULL');const warnings=[];for(const lang of ['en','ar'] as const){const titles=new Set<string>();for(const page of pages){const data=page.published[lang],title=data.seoTitle||data.title;if(!title)warnings.push(`${lang}/${page.slug}: missing title`);if(titles.has(title))warnings.push(`${lang}/${page.slug}: duplicate title`);titles.add(title);if(!data.description)warnings.push(`${lang}/${page.slug}: using default description`);}}if(!seo.googleVerification)warnings.push('Google verification is not configured (optional).');if(!seo.indexable)warnings.push('Public indexing is disabled.');return {settings:seo,revision:(await one('SELECT revision FROM seo_settings WHERE id=1'))!.revision,warnings};});
 app.put('/api/admin/seo',async req=>{const actor=admin(req),input=z.object({settings:seoSchema,expectedRevision:z.number().int().positive()}).parse(req.body);if(input.settings.trackingEnabled)throw new ApiError(400,'Analytics identifiers can be prepared here. Tracking remains disabled until a consent integration is installed.','TRACKING_NOT_CONFIGURED');requireValue(await one('UPDATE seo_settings SET value=$1,revision=revision+1,updated_at=now() WHERE id=1 AND revision=$2 RETURNING id',[JSON.stringify(input.settings),input.expectedRevision]),'SEO settings changed. Reload before saving.');await audit(actor.id,'seo.updated','public',{},req.ip);return {ok:true};});
 app.get('/robots.txt',async(_,reply)=>{const seo=await seoSettings(),base=(seo.canonicalBase||env.APP_ORIGIN).replace(/\/$/,'');return reply.type('text/plain').send(`User-agent: *\n${seo.indexable?['/admin','/account','/drive','/api','/s/','/support','/login','/register','/reset','/verify'].map(p=>`Disallow: ${p}`).join('\n'):'Disallow: /'}\nSitemap: ${base}/sitemap.xml\n`);});
 app.get('/sitemap.xml',async(_,reply)=>{const seo=await seoSettings(),base=(seo.canonicalBase||env.APP_ORIGIN).replace(/\/$/,''),pages=seo.indexable?await query('SELECT slug,published,updated_at FROM cms_pages WHERE published IS NOT NULL AND (published->>\'indexable\')::boolean'):[];return reply.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.flatMap(p=>['ar','en'].map(lang=>`<url><loc>${escapeHtml(p.published[lang].canonical||base+pagePath(lang,p.slug))}</loc><lastmod>${new Date(p.updated_at).toISOString()}</lastmod></url>`)).join('')}</urlset>`);});
 app.get('/',async(_,reply)=>reply.redirect('/en',302));
 if(existsSync(path.resolve('dist/web/index.html'))){const template=await readFile('dist/web/index.html','utf8');for(const lang of ['en','ar'] as const)for(const route of [`/${lang}`,`/${lang}/:slug`])app.get(route,async(req,reply)=>{const slug=(req.params as {slug?:string}).slug??'home';const page=await publicPage(slug,lang);let html=template.replace(/<title>.*?<\/title>/s,'').replace(/<meta name="description"[^>]*>/,'').replace('</head>',head(page)+'</head>').replace(/<html[^>]*>/,`<html lang="${lang}" dir="${lang==='ar'?'rtl':'ltr'}">`);html=html.replace('<div id="root"></div>',`<div id="root"><main class="public-main"><article class="content-page"><h1>${escapeHtml(page.title)}</h1>${page.html}</article></main></div>`);return reply.header('X-Robots-Tag',page.meta.indexable?'index,follow':'noindex,nofollow').type('text/html').send(html);});}
}
