import type {FastifyInstance,FastifyRequest} from 'fastify';
import {z} from 'zod';
import {randomUUID} from 'node:crypto';
import {env} from '../../../packages/config/index.js';
import {one,query,tx,audit,type DB} from '../../../packages/database/index.js';
import {capability,ticketLookup,ticketLookups,encryptField,decryptField} from '../../../packages/privacy/index.js';
import {support,requireIdentity} from './auth.js';
import {ApiError,requireValue,limited,hash,randomToken} from './lib.js';
import {paramId} from './files.js';
const category=z.enum(['GENERAL','TECHNICAL','ACCOUNT','UPLOAD','DOWNLOAD','FILE_SHARE','ABUSE','COPYRIGHT','OTHER']);
async function authorize(req:FastifyRequest,id:string){const row=requireValue(await one('SELECT id,owner_id,category,status,created_at,updated_at,subject_ciphertext FROM support_tickets WHERE id=$1',[id]));if(row.owner_id){if(row.owner_id!==req.user?.id)throw new ApiError(404,'Ticket unavailable.');}else{const token=req.cookies[`astra_ticket_${id.replaceAll('-','')}`];if(!token||!await one('SELECT 1 FROM support_access WHERE ticket_id=$1 AND token_hash=$2 AND expires_at>now()',[id,hash(token)]))throw new ApiError(404,'Ticket unavailable.');}return row;}
const ticketView=(row:any)=>{const {subject_ciphertext,capability_digest,...safe}=row;return {...safe,subject:decryptField(subject_ciphertext,`ticket-subject:${row.id}`)};};
async function message(db:DB,ticketId:string,actor:string|null,body:string,staff=false,internal=false){const id=randomUUID();await query('INSERT INTO support_messages(id,ticket_id,actor_id,body_ciphertext,staff,internal) VALUES($1,$2,$3,$4,$5,$6)',[id,ticketId,actor,encryptField(body,`ticket-message:${id}`),staff,internal],db);await query('UPDATE support_tickets SET updated_at=now() WHERE id=$1',[ticketId],db);}
async function messages(id:string,staff=false){return (await query(`SELECT id,staff,internal,body_ciphertext,created_at FROM support_messages WHERE ticket_id=$1 ${staff?'':'AND NOT internal'} ORDER BY created_at,id`,[id])).map(({body_ciphertext,...row})=>({...row,body:decryptField(body_ciphertext,`ticket-message:${row.id}`)}));}
export async function supportRoutes(app:FastifyInstance){
 app.post('/api/support/tickets',async req=>{await limited(`contact:${req.user?.id??req.ip}`,5,3600);const input=z.object({category,subject:z.string().trim().min(3).max(160),message:z.string().trim().min(10).max(12000),website:z.string().max(100).optional()}).parse(req.body);if(input.website)throw new ApiError(400,'Unable to submit this request.');const id=randomUUID(),ownerId=req.user&&!req.user.anonymous?req.user.id:null,secret=ownerId?null:capability();await tx(async db=>{await query('INSERT INTO support_tickets(id,owner_id,capability_digest,category,subject_ciphertext) VALUES($1,$2,$3,$4,$5)',[id,ownerId,secret?ticketLookup(secret):null,input.category,encryptField(input.subject,`ticket-subject:${id}`)],db);await message(db,id,ownerId,input.message);await audit(ownerId,'support.created',id,{category:input.category},req.ip,db);});return {id,...(secret?{url:`${env.APP_ORIGIN}/support/#${secret}`}:{})};});
 app.post('/api/support/resolve',async(req,reply)=>{await limited(`ticket-resolve:${req.ip}`,30,60);const {secret}=z.object({secret:z.string().regex(/^[A-Za-z0-9_-]{43}$/)}).parse(req.body);const ticket=requireValue(await one('SELECT id FROM support_tickets WHERE capability_digest=ANY($1::text[])',[ticketLookups(secret)]),'Ticket unavailable.');const token=randomToken();await query("INSERT INTO support_access(token_hash,ticket_id,expires_at) VALUES($1,$2,now()+interval '1 hour')",[hash(token),ticket.id]);reply.setCookie(`astra_ticket_${ticket.id.replaceAll('-','')}`,token,{secure:true,httpOnly:true,sameSite:'strict',path:`/api/support/tickets/${ticket.id}`,maxAge:3600});return {id:ticket.id};});
 app.get('/api/support/tickets',async req=>({items:(await query('SELECT id,subject_ciphertext,category,status,created_at,updated_at FROM support_tickets WHERE owner_id=$1 ORDER BY updated_at DESC LIMIT 100',[requireIdentity(req).id])).map(ticketView)}));
 app.get('/api/support/tickets/:id',async req=>{const ticket=await authorize(req,paramId(req));return {ticket:ticketView(ticket),messages:await messages(ticket.id)};});
 app.post('/api/support/tickets/:id/messages',async req=>{const id=paramId(req),ticket=await authorize(req,id);await limited(`ticket-reply:${id}:${req.ip}`,20,3600);const {body}=z.object({body:z.string().trim().min(1).max(12000)}).parse(req.body);if(ticket.status==='CLOSED')throw new ApiError(409,'This ticket is closed. Create a new request if needed.');await tx(db=>message(db,id,req.user?.id??null,body));return {ok:true};});
 app.get('/api/admin/support',async req=>{support(req);const input=z.object({status:z.enum(['','OPEN','IN_PROGRESS','CLOSED']).default(''),category:category.or(z.literal('')).default(''),q:z.string().max(160).default(''),offset:z.coerce.number().int().min(0).max(100000).default(0)}).parse(req.query);const rows=await query("SELECT t.id,t.subject_ciphertext,t.category,t.status,t.assignee_id,t.created_at,t.updated_at,u.account_id FROM support_tickets t LEFT JOIN users u ON u.id=t.owner_id WHERE ($1='' OR t.status=$1) AND ($2='' OR t.category=$2) ORDER BY t.updated_at DESC",[input.status,input.category]);const items=rows.map(ticketView).filter(t=>!input.q||[t.subject,t.account_id??'',t.id].some(v=>v.toLowerCase().includes(input.q.toLowerCase())));return {items:items.slice(input.offset,input.offset+100),hasMore:items.length>input.offset+100,staff:await query("SELECT id,account_id,role FROM users WHERE role IN ('SUPPORT','MODERATOR','ADMIN','OWNER') AND status='ACTIVE' ORDER BY account_id")};});
 app.get('/api/admin/support/:id',async req=>{support(req);const row=requireValue(await one('SELECT t.*,u.account_id FROM support_tickets t LEFT JOIN users u ON u.id=t.owner_id WHERE t.id=$1',[paramId(req)]));return {ticket:ticketView(row),messages:await messages(row.id,true)};});
 app.patch('/api/admin/support/:id',async req=>{const actor=support(req),id=paramId(req);const input=z.object({status:z.enum(['OPEN','IN_PROGRESS','CLOSED']).optional(),assigneeId:z.uuid().nullable().optional()}).parse(req.body);await tx(async db=>{if(input.assigneeId)requireValue(await one("SELECT id FROM users WHERE id=$1 AND role IN ('SUPPORT','MODERATOR','ADMIN','OWNER') AND status='ACTIVE'",[input.assigneeId],db));requireValue(await one("UPDATE support_tickets SET status=COALESCE($2,status),assignee_id=CASE WHEN $3 THEN $4::uuid ELSE assignee_id END,closed_at=CASE WHEN $2='CLOSED' THEN now() WHEN $2 IN ('OPEN','IN_PROGRESS') THEN NULL ELSE closed_at END,updated_at=now() WHERE id=$1 RETURNING id",[id,input.status??null,input.assigneeId!==undefined,input.assigneeId??null],db));await audit(actor.id,'support.updated',id,input,req.ip,db);});return {ok:true};});
 app.post('/api/admin/support/:id/messages',async req=>{const actor=support(req),id=paramId(req),input=z.object({body:z.string().trim().min(1).max(12000),internal:z.boolean().default(false)}).parse(req.body);requireValue(await one('SELECT id FROM support_tickets WHERE id=$1',[id]));await tx(async db=>{await message(db,id,actor.id,input.body,true,input.internal);await audit(actor.id,input.internal?'support.note':'support.reply',id,{},req.ip,db);});return {ok:true};});
}
