import {useState,type FormEvent} from 'react';
import {Link,useNavigate,useLocation} from 'react-router-dom';
import {ArrowRight,KeyRound,ShieldCheck} from 'lucide-react';
import {useI18n} from '../i18n.js';
import {useApp} from '../context.js';
import {api} from '../api.js';
import {ErrorBox,useUI} from '../components.js';
export function AuthPage(){const{t}=useI18n(),{refresh}=useApp(),{toast}=useUI(),navigate=useNavigate(),location=useLocation();const kind=location.pathname.slice(1);const[error,setError]=useState(''),[busy,setBusy]=useState(false);const verify=kind==='verify',register=kind==='register',setup=kind==='setup',forgot=kind==='forgot',reset=kind==='reset';const title=verify?t('verifyEmail'):setup?t('setup'):register?t('signUp'):forgot?t('forgot'):reset?t('reset'):t('signIn');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{if(reset||verify)data.token=window.location.hash.slice(1);await api(`/auth/${kind==='login'?'login':kind}`,'POST',data);if(verify){history.replaceState(null,'','/verify');await refresh();toast(t('saveSuccess'));navigate('/account');return;}if(forgot){toast(t('sendReset'));return;}if(reset){history.replaceState(null,'','/reset');toast(t('saveSuccess'));navigate('/login');return;}await refresh();navigate('/drive');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="auth-page"><div className="auth-illustration"><span className="eyebrow">YOUR SPACE, SIMPLIFIED</span><h2>{t('dropTitle')}</h2><p>{t('securityInfo')}</p><div className="auth-art"><div/><div/><div/><ShieldCheck size={60} strokeWidth={1}/></div><small>{t('originalDetail')}</small></div><form className="auth-form" onSubmit={submit}><span className="auth-icon"><KeyRound size={24}/></span><h1>{title}</h1>{setup&&<p>{t('setupHelp')}</p>}{setup&&<label className="field"><span>{t('fullName')}</span><input name="name" autoComplete="name" required maxLength={80}/></label>}{!reset&&!verify&&<label className="field"><span>{t('email')}</span><input type="email" name="email" autoComplete="email" required/></label>}{!forgot&&!verify&&<label className="field"><span>{t('password')}</span><input aria-label={t('password')} name="password" type="password" autoComplete={register||setup||reset?'new-password':'current-password'} minLength={kind==='login'?1:12} maxLength={256} required/>{kind!=='login'&&<small>{t('passwordHelp')}</small>}</label>}{setup&&<label className="field"><span>{t('setupToken')}</span><input name="token" type="password" autoComplete="off" required/></label>}{error&&<ErrorBox message={error}/>}<button className="button full" disabled={busy}>{busy?t('loading'):title}<ArrowRight size={17}/></button>{kind==='login'&&<><Link to="/forgot" className="auth-link">{t('forgot')}</Link><p className="auth-switch"><Link to="/register">{t('signUp')}</Link></p></>}{register&&<p className="auth-switch"><Link to="/login">{t('signIn')}</Link></p>}</form></div>;
}
