import {useState} from 'react';
import {api,bytes} from '../api.js';
import {useI18n,type Key} from '../i18n.js';
import {useData,useUI,ErrorBox,Loading,Badge} from '../components.js';
export const policyKeys=['storageBytes','fileBytes','dailyBytes','monthlyBytes','bandwidthBytes','concurrentUploads','concurrentDownloads','shareCount','maxShareHours','versionCount','versionDays','apiEnabled'] as const;
export function PlansPage(){
 const {t}=useI18n(),{toast}=useUI(),{data,error,loading,reload}=useData('/admin/plans');const [editing,setEditing]=useState<any>(null),[busy,setBusy]=useState(false);
 async function save(){setBusy(true);try{await api(`/admin/plans/${editing.id}`,'PUT',{name:editing.name,enabled:editing.enabled,policy:editing.policy});setEditing(null);reload();toast(t('saveSuccess'));}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 if(loading&&!data)return <Loading/>;
 return <div><div className="page-title"><div><span className="eyebrow">{t('admin')}</span><h1>{t('plans')}</h1></div></div>{error&&<ErrorBox message={error}/>}<p className="muted">{t('planChangesNote')}</p>{editing?<form className="settings-form" onSubmit={e=>{e.preventDefault();void save();}}><h2>{editing.id}</h2><label className="field"><span>{t('name')}</span><input required maxLength={80} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})}/></label>{policyKeys.map(key=>key==='apiEnabled'?<label className="setting-toggle" key={key}><span>{t(key)}</span><input type="checkbox" checked={editing.policy[key]} onChange={e=>setEditing({...editing,policy:{...editing.policy,[key]:e.target.checked}})}/></label>:<label className="field" key={key}><span>{t(key as Key)}{key.endsWith('Bytes')?' (GiB)':''}</span><input required type="number" step={key.endsWith('Bytes')?'0.01':'1'} min={['shareCount','versionCount','versionDays'].includes(key)?0:1} value={editing.policy[key]/(key.endsWith('Bytes')?1024**3:1)} onChange={e=>setEditing({...editing,policy:{...editing.policy,[key]:Math.round(Number(e.target.value)*(key.endsWith('Bytes')?1024**3:1))}})}/></label>)}<div className="row-actions"><button className="button" disabled={busy}>{t('save')}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setEditing(null)}>{t('cancel')}</button></div></form>:<div className="health-cards">{data?.items.map((plan:any)=><section className="account-section" key={plan.id}><div className="section-heading"><h2>{plan.name}</h2><Badge>{plan.id}</Badge></div><dl className="storage-details">{policyKeys.map(key=><div key={key}><dt>{t(key as Key)}</dt><dd>{typeof plan.policy[key]==='boolean'?t(plan.policy[key]?'enable':'disabled'):key.endsWith('Bytes')?bytes(plan.policy[key]):plan.policy[key]}</dd></div>)}</dl><button className="button secondary" onClick={()=>setEditing(structuredClone(plan))}>{t('settings')}</button></section>)}</div>}</div>;
}
