import {useEffect,useState,type FormEvent} from 'react';
import {Save,ChevronRight} from 'lucide-react';
import {api} from '../api.js';
import {useI18n,type Key} from '../i18n.js';
import {useData,useUI,Loading,ErrorBox} from '../components.js';
const groups:Record<string,string[]>={general:['siteName','description','supportUrl','defaultLanguage','logoFileId','faviconFileId'],uploads:['anonymousEnabled','partMiB','concurrency','uploadTimeoutHours','anonymousRetentionDays','blockedExtensions','anonymousConcurrentUploads','incompleteUploadLimit','incompleteReservedGiB','uploadCreatesPerMinute','uploadCreatesPerHour','failedUploadThreshold','uploadCooldownMinutes'],sharing:['defaultShareHours','defaultMaxDownloads','sharePasswordsEnabled','anonymousSharingEnabled','trashDays','versioningEnabled','maxVersionCount','maxVersionDays'],users:['registrationEnabled','requireManualActivation','sessionDays','maxSessions'],security:['privacyRetentionDays','apiPerMinute','anonymousCreatesPerHour','scanningEnabled'],storage:['minimumFreeGiB','warningFreeGiB','criticalFreeGiB'],appearance:['accent','defaultTheme','homepageTitle','homepageSubtitle'],maintenance:['maintenance','readOnly']};
export function SettingsPage(){const{t}=useI18n(),{toast}=useUI();const{data,error,loading,reload}=useData('/admin/settings');const{data:images}=useData('/files?type=image');const[value,setValue]=useState<any>(null),[group,setGroup]=useState('general'),[role,setRole]=useState('USER'),[busy,setBusy]=useState(false);useEffect(()=>{if(data)setValue(data.settings);},[data]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api('/admin/settings','PUT',value);toast(t('saveSuccess'));reload();}catch(e){toast((e as Error).message);}finally{setBusy(false);}}
 if(loading&&!data)return <Loading/>;if(error)return <ErrorBox message={error}/>;if(!value)return null;
 return <div><div className="page-title"><div><span className="eyebrow">{t('admin')}</span><h1>{t('settings')}</h1></div><button className="button" form="settings-form" disabled={busy}><Save size={17}/>{t('save')}</button></div><div className="settings-layout"><nav className="settings-nav" aria-label={t('settings')}>{[...Object.keys(groups),'quota'].map(key=><button key={key} className={group===key?'active':''} onClick={()=>setGroup(key)}>{t(key as Key)}<ChevronRight size={15}/></button>)}</nav><form id="settings-form" className="settings-form" onSubmit={submit}><h2>{t(group as Key)}</h2>{group==='quota'?<><label className="field"><span>{t('role')}</span><select value={role} onChange={e=>setRole(e.target.value)}>{Object.keys(value.quotas).map(r=><option key={r}>{r}</option>)}</select></label>{Object.keys(value.quotas[role]).map(key=><label className="field" key={key}><span>{t(key as Key)} (GiB)</span><input type="number" step="0.01" min="0.01" value={value.quotas[role][key]/1024**3} onChange={e=>setValue({...value,quotas:{...value.quotas,[role]:{...value.quotas[role],[key]:Math.round(Number(e.target.value)*1024**3)}}})}/></label>)}</>:groups[group].map(key=>typeof value[key]==='boolean'?<label className="setting-toggle" key={key}><div><strong>{t(key as Key)}</strong>{key==='scanningEnabled'&&!data.scannerConfigured&&<small>{t('unavailable')}</small>}</div><input type="checkbox" role="switch" checked={value[key]??''} onChange={e=>setValue({...value,[key]:e.target.checked})}/></label>:<label className="field" key={key}><span>{key==='defaultLanguage'?t('language'):key==='accent'?t('brand'):t(key as Key)}</span>{['logoFileId','faviconFileId'].includes(key)?<select value={value[key]??''} onChange={e=>setValue({...value,[key]:e.target.value||null})}><option value="">AstraFile</option>{images?.items?.filter((f:any)=>f.size<=1048576).map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select>:key==='defaultLanguage'||key==='accent'||key==='partMiB'||key==='defaultTheme'?<select value={value[key]??''} onChange={e=>setValue({...value,[key]:key==='partMiB'?Number(e.target.value):e.target.value})}>{(key==='defaultTheme'?['dark','light','system']:key==='defaultLanguage'?['en','ar']:key==='accent'?['teal','blue','violet']:[32,64,128,256]).map(v=><option key={v}>{v}</option>)}</select>:<input type={typeof value[key]==='number'||key==='defaultMaxDownloads'?'number':'text'} value={Array.isArray(value[key])?value[key].join(', '):value[key]??''} onChange={e=>setValue({...value,[key]:key==='defaultMaxDownloads'?(e.target.value?Number(e.target.value):null):key==='blockedExtensions'?e.target.value.split(',').map(s=>s.trim()).filter(Boolean):typeof value[key]==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</form></div></div>;
}
