import {useState,useEffect,type FormEvent} from 'react';
import {useParams,Link} from 'react-router-dom';
import {Download,LockKeyhole,ShieldCheck,ArrowUpRight,Flag,Eye} from 'lucide-react';
import {api,bytes,date,RequestError} from '../api.js';
import {useI18n} from '../i18n.js';
import {useData,Loading,ErrorBox,FileIcon,IconButton,useUI,Badge,Empty} from '../components.js';
import {previewDialog} from './Drive.js';
export function SharePage(){const{slug:legacySecret}=useParams(),{t,lang}=useI18n(),{dialog,toast}=useUI();const[slug,setShareId]=useState<string|null>(null),[resolved,setResolved]=useState(false),[resolveError,setResolveError]=useState(''),[resolveCode,setResolveCode]=useState('');
 useEffect(()=>{let active=true;void(async()=>{try{const secret=window.location.hash.slice(1)||legacySecret;if(secret){const result=await api('/shares/resolve','POST',{secret});if(!active)return;sessionStorage.setItem('astra:share-id',result.shareId);history.replaceState(null,'','/s/');setShareId(result.shareId);}else{const id=sessionStorage.getItem('astra:share-id');if(!id)throw Error(t('shareUnavailable'));if(active)setShareId(id);}}catch(e){if(active){setResolveError((e as Error).message);setResolveCode((e as RequestError).code??'SHARE_SESSION');}}finally{if(active)setResolved(true);}})();return()=>{active=false;};},[legacySecret]);
 const feed=useData(slug?`/public/shares/${slug}`:null),{data,reload}=feed,error=resolveError||feed.error,errorCode=resolveCode||feed.errorCode,loading=!resolved||feed.loading;const[password,setPassword]=useState(''),[unlockError,setUnlockError]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false);
 async function unlock(e:FormEvent){e.preventDefault();setUnlockError('');setBusy(true);try{await api(`/public/shares/${slug}/unlock`,'POST',{password});setPassword('');reload();}catch(e){setUnlockError((e as Error).message);}finally{setBusy(false);}}
 async function download(f:any,preview=false){try{const r=await api(`/public/shares/${slug}/download`,'POST',{fileId:f.id,preview});if(preview)await previewDialog(dialog,t,r);else{const a=document.createElement('a');a.href=r.url;a.rel='noreferrer';a.download=f.name;document.body.append(a);a.click();a.remove();}}catch(e){toast((e as Error).message);}}
 async function report(){await dialog({title:t('report'),fields:[{name:'reason',label:t('reason'),type:'textarea',required:true}],confirm:t('submit'),onSubmit:async v=>{await api(`/public/shares/${slug}/report`,'POST',v);toast(t('saveSuccess'));}});}
 if(loading)return <Loading/>;
 if(error&&errorCode!=='SHARE_PASSWORD')return <div className="share-locked"><div className="lock-icon"><LockKeyhole size={30}/></div><h1>{t('shareUnavailable')}</h1><ErrorBox message={error}/>{errorCode==='PRIVATE_SHARE'?<Link className="button" to="/login">{t('signIn')}</Link>:<Link className="button secondary" to="/">{t('newUpload')}</Link>}</div>;
 if(error)return <div className="share-locked"><div className="lock-icon"><LockKeyhole size={30}/></div><h1>{t('protectedShare')}</h1><p className="muted">{error}</p><form onSubmit={unlock}><label className="field"><span>{t('password')}</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label>{unlockError&&<ErrorBox message={unlockError}/>}<button className="button full" disabled={busy}>{t('unlock')}</button></form><Link to="/login">{t('signIn')}</Link></div>;
 return <div className="public-share"><div className="share-heading"><span className="eyebrow">{t('sharedWithYou')}</span><h1>{data.share.name}</h1><div className="share-meta"><span>{data.files.length} {t('files')}</span><span>{bytes(data.files.reduce((n:number,f:any)=>n+f.size,0))}</span>{data.share.expiresAt&&<span>{t('expires')} {date(data.share.expiresAt,lang)}</span>}</div></div><div className="share-files"><div className="section-heading"><h2>{t('files')}</h2>{selected.length>0&&<button className="button" onClick={()=>void(async()=>{for(const f of data.files.filter((f:any)=>selected.includes(f.id)))await download(f);})()}><Download size={17}/>{t('downloadAll')} ({selected.length})</button>}</div>{data.files.length?data.files.map((f:any)=><div className="public-file" key={f.id}><input type="checkbox" aria-label={f.name} checked={selected.includes(f.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,f.id]:s.filter(id=>id!==f.id))}/><FileIcon mime={f.detected_mime}/><div className="public-file-name"><strong>{f.name}</strong><span>{bytes(f.size)} · {date(f.created_at,lang)}</span></div><IconButton label={t('preview')} onClick={()=>void download(f,true)}><Eye size={18}/></IconButton><button className="button secondary" onClick={()=>void download(f)}><Download size={17}/><span>{t('download')}</span></button></div>):<Empty title={t('empty')}/>}</div><p className="privacy-note"><ShieldCheck size={15}/>{t('originalDetail')}</p><div className="share-footer"><small>{t('signedNote')}</small><button onClick={()=>void report()}><Flag size={13}/>{t('report')}</button></div><div className="share-cta"><div><h3>{t('dropTitle')}</h3><p>{t('dropSub')}</p></div><Link className="button secondary" to="/">{t('newUpload')}<ArrowUpRight size={16}/></Link></div></div>;
}
