import {useEffect,useState} from 'react';
import {Link,useLocation,useNavigate,useParams} from 'react-router-dom';
import {api,date} from '../api.js';
import {useI18n,type Key} from '../i18n.js';
import {useApp} from '../context.js';
import {useData,useUI,ErrorBox,Loading,LinkResult,Empty,Badge} from '../components.js';
const categories=['GENERAL','TECHNICAL','ACCOUNT','UPLOAD','DOWNLOAD','FILE_SHARE','ABUSE','COPYRIGHT','OTHER'];
function TicketMessages({data,staff=false,path,reload}:{data:any;staff?:boolean;path:string;reload:()=>void}){
 const {t,lang}=useI18n(),{toast}=useUI(),[body,setBody]=useState(''),[internal,setInternal]=useState(false),[busy,setBusy]=useState(false);
 return <><div className="ticket-messages">{data.messages.map((message:any)=><article className="account-section" key={message.id}><div className="section-heading"><Badge>{t(message.internal?'internalNote':message.staff?'support':'customer')}</Badge><small>{date(message.created_at,lang)}</small></div><p className="ticket-body">{message.body}</p></article>)}</div><form onSubmit={event=>{event.preventDefault();setBusy(true);void api(`${path}/messages`,'POST',{body,...(staff?{internal}:{})}).then(()=>{setBody('');reload();toast(t('saveSuccess'));}).catch(e=>toast(e.message)).finally(()=>setBusy(false));}}><label className="field"><span>{t('reply')}</span><textarea required maxLength={12000} value={body} onChange={e=>setBody(e.target.value)}/></label>{staff&&<label className="setting-toggle"><span>{t('internalNote')}</span><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/></label>}<button className="button" disabled={busy||!staff&&data.ticket.status==='CLOSED'}>{t('sendReply')}</button></form></>;
}
export function SupportPage(){
 const {id}=useParams(),location=useLocation(),navigate=useNavigate(),{user}=useApp(),{t,lang}=useI18n(),{dialog,toast}=useUI();const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const ticket=useData(id?`/support/tickets/${id}`:null),list=useData(!id&&user&&!user.anonymous?'/support/tickets':null);
 useEffect(()=>{const secret=location.hash.slice(1);if(secret)void api('/support/resolve','POST',{secret}).then(result=>navigate(`/support/t/${result.id}`,{replace:true})).catch(e=>setError(e.message));},[location.hash]);
 useEffect(()=>{if(!id)return;const timer=setInterval(()=>{if(!document.hidden)ticket.reload();},15000);return()=>clearInterval(timer);},[id]);
 async function submit(form:HTMLFormElement){setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(form));const result=await api('/support/tickets','POST',values);if(result.url){await dialog({title:t('ticketCreated'),description:t('ticketSecretNote'),content:<LinkResult url={result.url}/>,confirm:t('close')});const resolved=await api('/support/resolve','POST',{secret:new URL(result.url).hash.slice(1)});navigate(`/support/t/${resolved.id}`);}else navigate(`/support/t/${result.id}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(id)return <div className="content-page"><Link to="/support">{t('support')}</Link>{ticket.error?<ErrorBox message={ticket.error}/>:!ticket.data?<Loading/>:<><h1>{ticket.data.ticket.subject}</h1><Badge>{ticket.data.ticket.status}</Badge><TicketMessages data={ticket.data} path={`/support/tickets/${id}`} reload={ticket.reload}/></>}</div>;
 return <div className="content-page"><h1>{t('support')}</h1><p>{t('contactPrivacyNote')}</p>{error&&<ErrorBox message={error}/>}<form onSubmit={event=>{event.preventDefault();void submit(event.currentTarget);}}><label className="field"><span>{t('category')}</span><select name="category" defaultValue={new URLSearchParams(location.search).get('category')??'GENERAL'}>{categories.map(category=><option value={category} key={category}>{t(category as Key)}</option>)}</select></label><label className="field"><span>{t('subject')}</span><input name="subject" required minLength={3} maxLength={160}/></label><label className="field"><span>{t('message')}</span><textarea name="message" required minLength={10} maxLength={12000}/></label><input className="honeypot" tabIndex={-1} aria-hidden="true" name="website" autoComplete="off"/><button className="button" disabled={busy}>{t('createTicket')}</button></form>{list.data&&<section className="account-section"><h2>{t('yourTickets')}</h2>{list.data.items.map((row:any)=><div className="session" key={row.id}><Link to={`/support/t/${row.id}`}>{row.subject}</Link><Badge>{row.status}</Badge><small>{date(row.updated_at,lang)}</small></div>)}</section>}</div>;
}
export function SupportInbox(){
 const {id}=useParams(),{t,lang}=useI18n(),{toast}=useUI(),[status,setStatus]=useState(''),[category,setCategory]=useState(''),[q,setQ]=useState(''),[search,setSearch]=useState(''),[offset,setOffset]=useState(0);useEffect(()=>setOffset(0),[status,category,q]);const listing=useData(`/admin/support?status=${status}&category=${category}&q=${encodeURIComponent(q)}&offset=${offset}`),detail=useData(id?`/admin/support/${id}`:null);
 const change=(body:unknown)=>void api(`/admin/support/${id}`,'PATCH',body).then(()=>{detail.reload();listing.reload();toast(t('saveSuccess'));}).catch(e=>toast(e.message));
 if(id)return <div><Link to="/admin/support">{t('contactInbox')}</Link>{detail.error?<ErrorBox message={detail.error}/>:!detail.data?<Loading/>:<><div className="page-title"><h1>{detail.data.ticket.subject}</h1></div><p>{detail.data.ticket.account_id??t('guest')}</p><div className="row-actions"><label className="field"><span>{t('status')}</span><select value={detail.data.ticket.status} onChange={e=>change({status:e.target.value})}>{['OPEN','IN_PROGRESS','CLOSED'].map(status=><option value={status} key={status}>{t(status as Key)}</option>)}</select></label><label className="field"><span>{t('assignment')}</span><select value={detail.data.ticket.assignee_id??''} onChange={e=>change({assigneeId:e.target.value||null})}><option value="">{t('unassigned')}</option>{listing.data?.staff.map((staff:any)=><option value={staff.id} key={staff.id}>{staff.account_id}</option>)}</select></label></div><TicketMessages data={detail.data} staff path={`/admin/support/${id}`} reload={detail.reload}/></>}</div>;
 return <div><div className="page-title"><h1>{t('contactInbox')}</h1></div><div className="file-toolbar"><form className="search" onSubmit={event=>{event.preventDefault();setQ(search);}}><input aria-label={t('search')} placeholder={t('search')} value={search} onChange={e=>setSearch(e.target.value)}/></form><select aria-label={t('status')} value={status} onChange={e=>setStatus(e.target.value)}><option value="">{t('all')}</option>{['OPEN','IN_PROGRESS','CLOSED'].map(status=><option value={status} key={status}>{t(status as Key)}</option>)}</select><select aria-label={t('category')} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t('all')}</option>{categories.map(category=><option value={category} key={category}>{t(category as Key)}</option>)}</select></div>{listing.error&&<ErrorBox message={listing.error}/>}<div className="table-wrap"><table><thead><tr><th>{t('subject')}</th><th>{t('accountId')}</th><th>{t('category')}</th><th>{t('status')}</th><th>{t('lastUpdated')}</th></tr></thead><tbody>{listing.data?.items.map((row:any)=><tr key={row.id}><td><Link to={`/admin/support/${row.id}`}>{row.subject}</Link></td><td>{row.account_id??t('guest')}</td><td>{t(row.category as Key)}</td><td>{t(row.status as Key)}</td><td>{date(row.updated_at,lang)}</td></tr>)}</tbody></table></div>{listing.data?.items.length===0&&<Empty title={t('noData')}/>}<div className="row-actions"><button className="button secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-100))}>{t('previous')}</button><button className="button secondary" disabled={!listing.data?.hasMore} onClick={()=>setOffset(offset+100)}>{t('next')}</button></div></div>;
}
